uPortal-Project/uportal-home

src/main/webapp/partials/marketplace-portlet.html
=> MUMUP-1467 : change home to favorite on app place

angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
=> MUMPO-409: Consistent sidebar menu color in /web

angularjs-portal-frame/pom.xml, angularjs-portal-home/pom.xml, pom.xml
Releases to uw-releases and uw-snapshot on code.doit
=> MUMUP-1472 : angularjs-portal is now versioned and deployable using release plugin

angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
Is this better @vertein? :P #onelinechangesets
=> MUMPO-407: add delay to drag and drop

angularjs-portal-frame/src/main/webapp/bucky/common/less/content.less, angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js, angularjs-portal-frame/src/main/webapp/js/main/main-service.js, angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html, angularjs-portal-frame/src/main/webapp/samples/sidebar.json
During MUMUP-1497 I realized that it would be nice if the sidebar was a bit more flexible. So... I did that.
=> Sidebar dynamic

angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html, angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
+ Fixed brokenness with deleting a portlet not updating the cache of marketplace entries
+ fixed 404 for an Angularish src url.
=> Minor fix for remove app & sidebar

angularjs-portal-frame/src/main/webapp/css/buckyless/cards.less, angularjs-portal-frame/src/main/webapp/css/buckyless/general.less, angularjs-portal-frame/src/main/webapp/css/buckyless/sidebar.less, angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html
Some small changes so that /web plays nice with the UW UI toolkit and so that undesirable styles aren't injected into /portal.
=> Cleanup to make things play nice

angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js, angularjs-portal-home/src/main/webapp/partials/static-content-card.html
Now that we have an option for static content, lets make it work again.
There was some class changes and styling changes which made it not work so well. This change cleans that up.
=> Fix static content card so it works again

build.sh
Sad but true, need to `clean` to avoid keeping around removed stuff.
=> `mvn clean` in `build.sh`.

angularjs-portal-frame/src/main/webapp/js/controllers.js, angularjs-portal-home/src/main/webapp/partials/notification-bell.html, angularjs-portal-home/src/main/webapp/partials/settings.html
+ We didn't need the settings controller since we are just setting `$storage` items that is already set on the higher up MainController scope. So I removed it.
+ Fixed the notification bell flag so it doesn't take a page refresh to see the change.
=> Remove unwanted settings controller and cleanup notification bell flag

angularjs-portal-home/src/main/webapp/partials/settings.html
People want grumpy cat, now you can have it.
After clicking current profile pic custom URL shows up
=> Custom URL for profile photo

angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js, angularjs-portal-frame/src/main/webapp/partials/header.html, angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html
Weirdness with a `ng-init` variable with attempting to access it in a child controller instance. Moved the variable to a variable on the header controller, accessing it that way works fine. #scopeIsWeird
=> MUMUP-1508 : Fix sidebar collapse on click of an element

angularjs-portal-frame/src/main/webapp/samples/sidebar.json, angularjs-portal-home/src/main/webapp/partials/settings.html
=> MUMMNG-1091 : Add my profile option to sidebar

angularjs-portal-frame/src/main/webapp/bower_components/uw-ui-toolkit/src/less/uw-ui-toolkit/my-uw/uw-myuw-portlet.less, angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html, angularjs-portal-home/src/main/webapp/partials/marketplace.html
Few more changes to account for new btn-default and btn-primary classes.
=> Add btn-default and btn-primary

angularjs-portal-home/src/main/webapp/partials/marketplace.html
=> MUMUP-1441: 'Show all' doesn't display hint

angularjs-portal-frame/src/main/webapp/css/buckyless/general.less, angularjs-portal-frame/src/main/webapp/index.html, angularjs-portal-home/src/main/webapp/index.html
=> MUMUP-1427 : add in error message for noscript

build-every-minute.sh
Adds a ridiculously bad shell script to build every minute.
Intended as a starting point for collaborating on something that would, say, only build on changes.
The thing is, I'm already finding this ridiculous script helpful to my flow.
=> Add a ridiculously bad build-every-minute script.

angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less
=> MUMUP-1512: Marketplace category clipping

angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less, angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
=> MUMUP-1535 : Details link doesn't do anything, until now

angularjs-portal-frame/src/main/webapp/js/services.js, angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js
+ Adds in logging for ga events for localhosting
+ Adds in event for filters. Note it does wait until the filter is actually filtered (currently has a 250ms delay)
=> MUMUP-1440 : Ga filter events

angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js, angularjs-portal-home/src/main/webapp/partials/default-card.html, angularjs-portal-home/src/main/webapp/partials/pithy-content-card.html, angularjs-portal-home/src/main/webapp/partials/portlet-icon.html, angularjs-portal-home/src/main/webapp/partials/static-content-card-max.html, angularjs-portal-home/src/main/webapp/partials/static-content-card.html, angularjs-portal-home/src/main/webapp/partials/static-content-max.html
=> MUMUP-1352 : Fix issue with empty icons and little refactor

angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
+ Related portlets now go to that marketplace entry by doing a search for the title
=> MUMUP-1539 : marketplace related app goes to marketplace entry

angularjs-portal-home/src/main/webapp/samples/new-stuff.json
Just persisting this to master so its consistent to what is in production
=> Added alert about css wohs

angularjs-portal-frame/src/main/webapp/css/buckyless/portlet-frame.less, angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less, angularjs-portal-home/src/main/webapp/partials/features.html, angularjs-portal-home/src/main/webapp/partials/layout.html, angularjs-portal-home/src/main/webapp/partials/marketplace.html, angularjs-portal-home/src/main/webapp/partials/static-content-max.html
Clean up on the static content max page, and fix the 60% paragraph bug on the new stuff div.
=> MUMUP-1559: Styling scrub, fix new stuff

angularjs-portal-frame/src/main/webapp/js/main/main-service.js, angularjs-portal-frame/src/main/webapp/js/services.js, angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js, angularjs-portal-home/src/main/webapp/js/layout/layout-services.js, angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-service.js
Related : https://github.com/UW-Madison-DoIT/uPortal/pull/318 
This is the changes to /web that make the related PR work.
Also cleaned up the redirect if someone has an invalid session.
Note that I would rather https://github.com/UW-Madison-DoIT/angularjs-portal/pull/132 merged before this is merged. This is much easier to cleanup than the other.
=> MUMUP-1522 : Fix redirect & point at /portal/web

angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
+ Reorganize list of services, etc..
+ add in `miscService.pushPageview()`
=> MUMMNG-1145 : add static page pagehit for ga

angularjs-portal-home/src/main/webapp/partials/layout.html, angularjs-portal-home/src/main/webapp/partials/marketplace-light.html
Minor change to make it so marketplace light is not sortable
=> Fix marketplace light so it isn't sortable

angularjs-portal-home/pom.xml, angularjs-portal-home/src/main/java/edu/wisc/my/home/api/GenericRestLookupController.java, angularjs-portal-home/src/main/java/edu/wisc/my/home/dao/GenericRestLookupDao.java, angularjs-portal-home/src/main/java/edu/wisc/my/home/dao/GenericRestLookupDaoImpl.java, angularjs-portal-home/src/main/java/edu/wisc/my/home/service/GenericRestLookupService.java, angularjs-portal-home/src/main/java/edu/wisc/my/home/service/GenericRestLookupServiceImpl.java, angularjs-portal-home/src/main/java/edu/wisc/my/home/util/KeyUtils.java, angularjs-portal-home/src/main/resources/.gitignore, angularjs-portal-home/src/main/resources/endpoint.properties.example, angularjs-portal-home/src/main/resources/logback.xml, angularjs-portal-home/src/main/webapp/WEB-INF/angularweb-api-servlet.xml, angularjs-portal-home/src/main/webapp/WEB-INF/views.xml, angularjs-portal-home/src/main/webapp/WEB-INF/web.xml, angularjs-portal-home/src/main/webapp/js/layout/layout-services.js, angularjs-portal-home/src/main/webapp/samples/new-stuff.json, angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts.json, pom.xml
+ Creates servlet for `/api`
+ Created a REST type end point with {key}.json where key is a preconfigured endpoint service
+ Uses basic auth or no authentication
+ Added an example properties file, must rename to have it work (will be in overlay)
+ Changed new stuff to point at servlet for an example of how we can utilize this new service.
=> MUMUP-1615 : Create servlet container, create configurable rest containers

angularjs-portal-frame/src/main/webapp/css/angular.less, angularjs-portal-frame/src/main/webapp/css/buckyless/home.less, angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-home/src/main/webapp/home.html, angularjs-portal-home/src/main/webapp/js/angular-page.js, angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js, angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js, angularjs-portal-home/src/main/webapp/js/layout/widget-controllers.js, angularjs-portal-home/src/main/webapp/partials/widget-card.html, angularjs-portal-home/src/main/webapp/partials/widgets/weather.html
Everyone loves knowing the weather. Therefore widget.
+ Adds `<weather></weather>` directive
+ Refactors widget controllers to widget-controllers.js
+ Shows your top 2 weather locations
+ Clicking the plus sign next to the location will show the 3 day forecast
+ This relates to https://github.com/Jasig/WeatherPortlet/pull/14 and https://github.com/UW-Madison-DoIT/uPortal/pull/323
+ note this was just a first pass, i know ux and ui will be polished/updated
=> MUMUP-1711 : Weather widget

angularjs-portal-home/src/main/webapp/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/partials/home-widget-view.html
=> MUMUP-1713 : Fix marketplace-light so its not draggable

angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less, angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less, angularjs-portal-home/src/main/webapp/partials/marketplace.html
Dev Notes
+ Change marketplace header to 200px (from 300px)
+ Removed paragraph describing apps
=> MUMUP-1669 : Remove paragraph about apps. Make header smaller

angularjs-portal-home/src/main/webapp/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/partials/home-widget-view.html, angularjs-portal-home/src/main/webapp/partials/widgets/option-link.html, angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts-1.json
+ Cleaned up marketplace light
+ Fixed if linked array isn't in email-widget
=> MUMUP-1713 & MUMUP-1709 : Cleanup favorite + thing, fix if linked is missing

angularjs-portal-home/src/main/webapp/WEB-INF/web.xml
Add in the filter for tomcat to put expiration dates on responses of various media types.
* `image/*` will be 1 month
* `text/*` will be 1 day
* `application/javascript` will be 1 day
* `application/json` will be 10 minutes
All subject to change.
=> MUMUP-1726 : Fix caching with some starting point expire defaults

angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js, angularjs-portal-frame/src/main/webapp/partials/settings.html, angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
Widget static content is no longer hidden behind a beta flag
=> MUMUP-1732 : Widget static content (pithy) is no longer made out of wood

angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js, angularjs-portal-home/src/main/webapp/js/angular-page.js, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js, angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js, angularjs-portal-home/src/main/webapp/partials/home-header.html, angularjs-portal-home/src/main/webapp/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/partials/home-toggle.html, angularjs-portal-home/src/main/webapp/partials/home-widget-view.html, angularjs-portal-home/src/test/setup.sh, angularjs-portal-home/src/test/spec/controllers/toggle_controller_spec.js
+ Creates toggle directive that manages which one you should be on
+ Adds sanity checking to make sure you are on the correct view
+ Consolidates exactly same code to home header
+ Moves page view to toggle to remove duplicate page hits
+ Resets to default if someone tries playing with localStorage
+ unit tests
+ Add in unit test setup.sh script for easy test setup
=> MUMUP-1746 : Sticky layout selection

angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less, angularjs-portal-frame/src/main/webapp/css/buckyless/myuw-toolkit-temporary.less, angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less, angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js, angularjs-portal-home/src/main/webapp/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
- Rate works
- Launch works
- Add to Home works
- Link back to App Marketplace
=> MUMUP-1749: Functional, not ugly marketplace details page

angularjs-portal-home/src/main/webapp/js/layout/widget-controllers.js
+ Adds in isEmpty flag so generic template widgets can utilize the loading-gif directive
+ Adds in config option `evalString` which would be a string that would be evaluated during a return call for emptiness.
=> MUMMNG-1262 : Add in isEmpty flag to genericController

angularjs-portal-frame/src/main/webapp/css/buckyless/myuw-toolkit-temporary.less, angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-frame/src/main/webapp/css/variables.less, angularjs-portal-home/src/main/webapp/partials/example-widgets.html
Some reusable styles for widgets, coming soon to a style guide near you. And an example for how to layout a widget.
=> Styles for Widgets

angularjs-portal-frame/src/main/webapp/samples/sidebar.json
Help is static content, changing to use the #/static/:fname
=> MUMUP-1717 : Move help to /web

angularjs-portal-home/src/main/webapp/js/main/search-controller.js
+ If one finds a result in the autocomplete that they like and they select it, it goes to the details page
+ If one just hits enter or the search button on the search, then it goes to marketplace with that filter
=> MUMUP-1770 : auto complete selection now goes to details

angularjs-portal-frame/src/main/webapp/bower.json
Adds the toolikit to bower.json
=> Adds uw-ui-toolkit to bower.json

angularjs-portal-frame/src/main/webapp/css/buckyless/home.less, angularjs-portal-frame/src/main/webapp/css/buckyless/myuw-toolkit-temporary.less, angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-home/src/main/webapp/partials/widgets/option-link.html
=> center things better

README.md
Does this make sense here? Will this minimize issues in the future? The lack of a manager role seems to be the problem I was having.
=> Update README to prevent future issues

angularjs-portal-frame/pom.xml, pom.xml
Updated WAR pom to remove unneeded dependencies - blocking development and not needed here
Updated Parent pom to update repository information
=> MUMUP-1816: Removed serlet from WAR, updated parent pom for updated repositories.

pom.xml
+ Remove parent so we don't distribute to uw-releases
+ Minor fix to URL for scm block
+ Update repository to public-releases
=> MUMUP-1789 : Update to public releases

angularjs-portal-frame/src/main/webapp/css/buckyless/home.less
=> MUMUP-1812: Smart widget hover state

angularjs-portal-home/src/main/webapp/partials/widget-card.html
=> MUMMNG-1305: Change default smart widget call-to-action to sentence case

angularjs-portal-frame/src/main/webapp/frame.html, angularjs-portal-frame/src/main/webapp/my-app.css
Eventually might want to make this a `less` file, but css to start. This is the same idea as the RequireJS work @paulerickson did recently. Give app devs a file to style anything they need to within their app.
=> Add my-app.css so app developers can style their apps

angularjs-portal-frame/src/main/webapp/css/buckyless/sidebar.less, angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html
Figured it out after much playing around.
=> MUMUP-1805: Fix funky popover

.travis.yml
Looks like we are all setup already on travis-ci.org, we just need the config file for builds to start.
=> Initial travis-ci configuration

angularjs-portal-frame/src/main/webapp/WEB-INF/web.xml, angularjs-portal-frame/src/main/webapp/frame.html, angularjs-portal-frame/src/main/webapp/js/angular-page.js, angularjs-portal-frame/src/main/webapp/partials/header.html, angularjs-portal-frame/src/main/webapp/samples/sidebar.json, angularjs-portal-home/src/main/webapp/WEB-INF/web.xml, angularjs-portal-home/src/main/webapp/home.html, angularjs-portal-home/src/main/webapp/js/angular-page.js, angularjs-portal-home/src/main/webapp/js/main/search-controller.js, angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js, angularjs-portal-home/src/main/webapp/partials/home-header.html, angularjs-portal-home/src/main/webapp/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/partials/marketplace-light.html, angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html, angularjs-portal-home/src/main/webapp/partials/notifications.html
So, I got HTML 5 mode to work. But we will need a server side component to this.
When you go to /web, you can go to /web/apps by clicking the sidebar, and angular will change the route/url for you. But if you refresh on that page, you get a 404 because the server doesn't know what to do with that. (Sidenote: I don't really understand how the server knows what to do with /web/#/apps though...is that this html5 mode magic?)
I will definitely need help with the server side part. @timlevett @mjadas do you know how we could do this?
=> MUMUP-1799: Hashless Links

angularjs-portal-frame/src/test/karma.conf.js, angularjs-portal-home/src/test/karma.conf.js
#202 && #185  broke our unit test scripts https://my-tools.doit.wisc.edu/jenkins/view/Projects/job/angularjs-portal-testing/103/console
This should fix it.
=> FIXIT: Karma good, failure bad

.codenvy/project.json, .codenvy/runners/environments/ENV1-angularjs-portal/Dockerfile, .codenvy/runners/environments/Multinode-tc7-j7/Dockerfile, README.md, angularjs-portal-frame/.codenvy/project.json, angularjs-portal-home/.codenvy/project.json, angularjs-portal-home/.codenvy/runners/environments/run-tc/Dockerfile, angularjs-portal-mock-portal/pom.xml, pom.xml
+ Adds in `codenvy` files
+ Adds in `codenvy` intructions to `README.md`
#tothecloud!
=> Get Codenvy Project Setup for angularjs-portal

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
Relates to https://github.com/UW-Madison-DoIT/uPortal/pull/352
+ Moves where to get the template
+ Add in error if the template is expected but not present
=> MUMUP-1818 : move widget template in layout feed

angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
+ Cleanup weather widget (MUMUP-1833)
+ Fix option link when you have options (button and drop down were colliding)
+ Fix option link when you have single option, centered text
=> Fix weather and option-link

angularjs-portal-frame/src/main/webapp/portal/misc/directives.js, angularjs-portal-frame/src/main/webapp/portal/settings/partials/settings.html
+ Adds the `reuse` attribute to the loading icon
+ Adds example to the /settings page for reuse and one time use
=> Add in ability to reuse loading icon

angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html
(more vertically centered)
Before:
After:
=> Minor style change for email widget

angularjs-portal-frame/src/main/webapp/css/buckyless/home.less, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html, angularjs-portal-home/src/main/webapp/samples/new-stuff.json
I'm not sure how this works across environments. Like, where is the new-stuff.json coming from in production? I may have implemented this wrong if there is a separate feed for each environment.
=> MUMMNG-1386: Messaging for widgets

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
If the user has no weather locations set, then the widget will provide a link to the UW-Madison institutional weather source (http://www.ssec.wisc.edu/localweather/).
=> MUMMNG-1396: Weather Widget should link to UW-Madison weather source

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-toggle.html
Triggers an event on click of both icon tabs - icon view and widget view.
=> MUMMNG-1393: Google Analytics for smart widgets

angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less, angularjs-portal-home/src/main/java/edu/wisc/my/home/util/KeyUtils.java, angularjs-portal-home/src/main/resources/endpoint.properties.example, angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
As an idea for our JSON example for our seminar, we could use subreddit, so I thought I would try it.
This is what I came up with.
I started with the `List of Content` sample widget (shown here https://tools.my.wisc.edu/widget-creator/samples). Then grabbed the subreddit feed for uwmadison. Then created an expandable reddit feed.
=> MUMMNG-1318 : Create a subreddit feed example widget

angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/settings/partials/settings.html, angularjs-portal-home/src/main/webapp/WEB-INF/web.xml, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/master-app-config.js, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/route.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/routes.js, angularjs-portal-home/src/main/webapp/my-app/main.js
I was trying to think of more fun quick things we could do for the Apereo seminar, and I got to thinking about rendering portlets in exclusive mode, kind of like the static page we have on `/web`. One thing led to another and... now there is a PR. 
+ Behind beta flag
+ Works with uPortal and MyUW
+ Flippin' works
+ JavaScript works (thanks to trusty `$sce`)
+ Forms, buttons, links that goto /portal (or /uPortal) render in exclusive mode on click, so... we have to deal with that sometime
+ Some portlets look funky
+ Didn't touch widgets, so beta flag is only for list view
+ Didn't setup add to favorite function (not hard tho)
+ Didn't setup rating (not hard tho)
=> MUMUP-1853 : Exclusive max mode

.gitignore, angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/main/partials/header.html, angularjs-portal-home/src/main/resources/logback.xml, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/master-app-config.js
=> MUMUP-1885 : Add in crest location externalization

angularjs-portal-frame/src/main/webapp/canary_test.js, angularjs-portal-frame/src/main/webapp/config.js, angularjs-portal-frame/src/main/webapp/karma.conf.js, angularjs-portal-frame/src/main/webapp/main.js, angularjs-portal-frame/src/main/webapp/package.json, angularjs-portal-frame/src/main/webapp/test/main.js
I ran `bower update`, forgetting that the test dependencies are actually in package.json, so the changeset looks bigger than it really is.  I figure it's good to keep updated, but let me know if you'd rather I reverted that part.
=> Set up karma testing

angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html
Add aria-label to dropdown-toggle (cog).
=> MUMUP-1902 aria-label the settings cog

angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Add description for search bar inside My Apps page.
issue:
MUMUP-1907 Bug : Search bar description
https://jira.doit.wisc.edu/jira/browse/MUMUP-1907
=> search bar inside My Apps page.

angularjs-portal-frame/src/main/webapp/portal/search/partials/search.html
issue:
MUM-1907 search bar - all pages
MUM-1908 search button - all pages
=> Add description - search bar & search button for all pages

angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/portal/search/controllers.js, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/master-app-config.js
Basically adds a redirect if its a frame app.  Has a shortcut for `/web` to avoid page refresh.
=> MUMUP-1943 : Add configuration to get frame apps search to work

angularjs-portal-frame/src/main/webapp/portal/main/partials/header.html
This will redirect to the context home (e.g. `/web`)
=> REGRESSION: Issue where header doesn't do anything on click

angularjs-portal-home/src/main/webapp/my-app/layout/partials/example-widgets.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-toggle.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
add description for switching symbols --- icons/widget view
=> Switch icon/widget view

angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/portal/notifications/controllers.js, angularjs-portal-frame/src/main/webapp/portal/notifications/partials/notification-bell.html, angularjs-portal-frame/src/main/webapp/portal/notifications/partials/notifications-full.html, angularjs-portal-frame/src/main/webapp/portal/notifications/partials/notifications.html, angularjs-portal-frame/src/main/webapp/portal/notifications/services.js, angularjs-portal-frame/src/main/webapp/samples/notifications.json, angularjs-portal-home/src/main/webapp/js/app-config.js
+ Refactored the controller to use `$scope`
+ Externalized some config for notifications for frame apps
+ Added `getNotificationsByGroups` to the `notificationsService`. This call does 2 http requests. 1 for groups, the other for notifications. Then it postprocesses to filter notifications by groups.
+ Added a new dummy notification for student group for testing
_No visual changes_
=> MUMUP-1856 : Notifications by group

angularjs-portal-frame/src/main/webapp/samples/notifications.json
=> MUMUP-1955 : Add in SSN missing notification for that group

angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/rating-modal-template.html
add description for star rating pop-up page's text edit box
=> add description for star rating pop-up page's text edit box

angularjs-portal-frame/src/main/webapp/css/buckyless/footer.less, angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/main/partials/footer.html, angularjs-portal-home/src/main/webapp/js/app-config.js
+ Adds config for `feedback`
+ Adds config for `back to classic`
+ Adds config for `what's new`
+ Adds back to classic to the footer, if its configured
+ Hides if not configured or `null`
=> MUMUP-1912 : Add in back to classic link and config

angularjs-portal-frame/src/main/webapp/frame.jsp, angularjs-portal-frame/src/main/webapp/portal/main/controllers.js
+ Fixed some spacing that was weird
+ Adds in a div for `sr-only` (bootstrappy thing) based on if they have a `back2classicURL` set. (good for frame apps opt out)
=> MUMUP-1925 : Add in opt out link on top of document for sr

angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/notifications/controllers.js, angularjs-portal-frame/src/main/webapp/portal/notifications/partials/notification-bell.html, angularjs-portal-frame/src/main/webapp/portal/settings/partials/settings.html, angularjs-portal-home/src/main/webapp/js/app-config.js
+ Removed beta notification flag in settings
+ Moved notification flag to app-config
=> MUMUP-1955 : remove alpha flag for notification. 

angularjs-portal-frame/src/main/webapp/portal/main/partials/welcome-modal-template.html
Thoughts on this? `aria-describedby` seems like the best option to me. But using a long alt text or using the `longdesc` option also seem legitimate.
=> Better accessibility for welcome popup image

angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
"MyUW Home" -> "Home"
https://www.youtube.com/watch?v=DHEOF_rcND8
=> MUMUP-1966: Home

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/rating-modal-template.html
add remove symbol description for removing from widgets view
=> Home page widgets view

angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
1. make the app can be delete from the home-page icon view by the cross symbol
2. add description to each app which will let the user know which app they are at before launching.
=> Home page icons view

angularjs-portal-frame/src/main/webapp/samples/sidebar.json, angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/marketplace-light.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-portlet.html
Add/Added to home instead of Add to home/Already in favorite
=> MUMUP-1986&1985 Change the "Add to favorites" & Already in favorites" button label 

angularjs-portal-frame/src/main/webapp/portal/main/partials/footer.html
+ target blank for some footer things
=> MUMUP-1716 : what's new = new window

angularjs-portal-frame/src/main/webapp/css/buckyless/home.less, angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
=> MUMUP-1969 : Make it a pretty button, and forget favorites

angularjs-portal-frame/src/main/webapp/js/app-config.js, angularjs-portal-frame/src/main/webapp/samples/sidebar.json, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/master-app-config.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-toggle.html, angularjs-portal-home/src/main/webapp/my-app/main.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
+ "{{TITLE}} Apps" changed names to "Search and Browse {{TITLE}}"
+ Sidebar updates from search to Browse with new FA icon
+ Mobile only shows "Search {{TITLE}}"
+ Changed list and widget to compact and expanded
+ Updated URLs as well for list/widget, note people that were widget will be redirected to compact
+ Not changing apps URL due to complexity
+ I'm not doing screenshots, but here is the doc: https://docs.google.com/presentation/d/1Bhi-XQ6HvQnPMyGko0L9tqdH2fNkULsygvOAhy0Vbf0/edit#slide=id.ga49f3c057_7_42
=> MUMUP-2000 : Change stuff

angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/settings/partials/settings.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-toggle.html
So we can have widget be default, and for america.
=> MUMUP-1999 : Remove beta flag on mobile toggle

angularjs-portal-frame/src/main/webapp/portal/main/partials/welcome-modal-template.html, angularjs-portal-home/src/main/webapp/samples/welcome.json
Some clean up things on the welcome. 
+ `ng-src` instead of `src` on the `img` tag
+ Enabled welcome for now
+ Made links show up if the were filled out, hidden if not
=> MUMUP-2019 : Change to ng-src and some minor things

angularjs-portal-frame/src/main/webapp/frame.jsp, angularjs-portal-frame/src/main/webapp/portal/main/controllers.js, angularjs-portal-frame/src/main/webapp/portal/main/services.js, angularjs-portal-frame/src/main/webapp/portal/notifications/controllers.js, angularjs-portal-frame/src/main/webapp/portal/notifications/services.js
+ Removes `ng-init` for welcome controller
+ Moves session service to create the promise later
+ Moves notification and group promise creations to later
=> MUMUP-2017 cleanup some http.get calls that might not be configured in frame

angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
=> EC : minor fix to label

.gitignore, angularjs-portal-home/pom.xml, angularjs-portal-home/src/main/webapp/css/my-app.less, angularjs-portal-home/src/main/webapp/my-app/.gitignore, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html, angularjs-portal-home/src/main/webapp/my-app/my-app.css, angularjs-portal-home/src/main/webapp/samples/new-stuff.json, angularjs-portal-home/src/main/webapp/samples/sidebar.json
+ Added sidebar to our overlay project
+ Added `my-app.less` with just a simple class. We can refactor uw-frame and this later
=> MUMUP-2029 : Add in styling specificially for home

angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html
could recognize all containers title on icon page now.
=> improve the accessibility for default/icon view

angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-portlet.html
Portlets' title able to get by TAB
the user will know which portlet it is before they "launch" it
the description of each app could able to read out.
"launch" described as "go to this app"
=> Accessibility improvement - search & browse MyUW page

angularjs-portal-home/src/main/webapp/samples/welcome.json
* Reflect new names for the compact and expanded widget mode toggles.
* Reflect "Add to home" rather than "Add to favorites" button label.
=> MUMUP-1969 Update accessibility text to reflect updated welcome image.

angularjs-portal-home/src/main/webapp/samples/notifications.json, angularjs-portal-mock-portal/src/main/webapp/api/groups
+ Move the MyUW specific notifications to angularjs-portal
+ Added in Activate Services notification 
Group came from the group the portlet is in. Text came from what the portlet currently says.
=> MUMMNG-1784 : Add in notification for user activation required

angularjs-portal-home/src/main/webapp/css/home.less, angularjs-portal-home/src/main/webapp/css/marketplace.less, angularjs-portal-home/src/main/webapp/css/my-app.less, angularjs-portal-home/src/main/webapp/css/uw-portlet.less, angularjs-portal-home/src/main/webapp/css/variables.less, angularjs-portal-home/src/main/webapp/css/widget.less
Corresponds to https://github.com/UW-Madison-DoIT/uw-frame/pull/11
=> move styles into /web

angularjs-portal-home/src/main/webapp/css/home.less
=> more padding on widget body

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
=> MUMUP-2054 : Add in rss widget type, add in example in mock data

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/js/master-app-config.js
=> relate to MyUW logo - come from MUMUP-2045

angularjs-portal-home/src/main/webapp/my-app/layout/list/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Add aria-landmark role usages in support of accessibility.
=>  MUMUP-2078 Home : aria-landmark role usages -[angularjs-portal]

angularjs-portal-home/src/main/webapp/samples/features.json
Updated features.json to be more accurate for our first welcome popup. If you want to test it out in your local environment from now on, you'll need to change the endDay and endMonth for it to appear.
=> MUMUP-2060: Clean splash seen-ness

angularjs-portal-home/src/main/webapp/css/home.less
"display:none / visibility:hidden / overflow:hidden " have the accessibility effect that content is ignored by screen readers
=> Solve the accessibility effect for CSS 'display' rules

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
Added the following configuration options for `<rss>`
+ `dateFormat` : The date format, see https://docs.angularjs.org/api/ng/filter/date
+ `showShowing` : show the Showing x of y (default `false`)
Here is an example with the `showShowing` off and a date with format `M/d`
=> MUMMNG-1857 : Adding more features to rss feed widget

angularjs-portal-home/src/main/webapp/css/widget.less
Fix the positioning and styling of buttons
=> Fix positioning/styling of weather widget buttons

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/samples/notifications.json, angularjs-portal-mock-portal/src/main/webapp/api/groups, angularjs-portal-mock-portal/src/main/webapp/getValue, angularjs-portal-mock-portal/src/main/webapp/setValue, pom.xml
+ Make a `/storage` in our `jetty:run` configuration
+ Move the `/getValue` and `/setValue` files so it works with `/storage`
+ Change `app-config.js` to `/storage/` for `kvURL`
+ Add in mocked up Employee benefits open enrollment for 2015
=> MUMMNG-1520 : Annual benefits enrollment 2015

angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
+ Fixed loading forever
+ Fixed mock data for weather icons as my-test.doit.wisc.edu no longer exists
=> MUMUP-2057 : Fix loading forever issue if you have help in your layout

angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
Fixed loading gif staying if you click on the link to the app from home screen
=> MUMUP-2057 : Static controller now stops loading

angularjs-portal-home/src/main/webapp/samples/notifications.json
Updates text of Annual Benefits Enrollment notification to use "Annual Benefits Enrollment" vs "open enrollment" and not use "th" on dates, per Service Center style preferences.
=> MUMMNG-1973 MUMMNG-1520 : tweak ABE notification text

angularjs-portal-home/src/main/webapp/WEB-INF/web.xml, angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/my-app/main.js
=> MUMUP-2127 : Add about stuff to angularjs-portal

angularjs-portal-home/src/main/webapp/samples/sidebar.json
Due to UW-Madison-DoIT/uw-frame#52 we need to cleanup `sidebar.json`
=> cleanup sidebar

angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
+ Comment out current header
+ Use `portlet-header` directive, smaller size, with variable background, no toggle
=> [WIP] Use directive for home

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Adds a list-of-links widget type to /web. This widget just displays a grid of four links using the circle link directive. The information about these links (href, title, target, icon) are provided by the `widgetConfig`. Entity file changes for other list-of-link widgets coming soon.
=> MUMMNG-2017: Make list-of-links widget type, LOL

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html
=> MUMMNG-2017: Support Manager time and approval as a list-of-links widget

.travis.yml, README.md, angularjs-portal-home/pom.xml, package.json
+ Get travis to run both uw-frame and angularjs-portal tests
+ Get travis to report coveralls coverage report
=> MUMUP-2284 : Coveralls support

README.md, angularjs-portal-home/src/main/webapp/js/master-app-config.js
Small changes to master app config to get it to work
Some small additions to the readme so that deploying is a bit easier.  Even deep links to frame documentation
=> Vanilla uPortal Documentation

README.md
Handful of typo fixes and style edits.
=> Copy edits for README.md

angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-portlet.html, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html, angularjs-portal-home/src/main/webapp/my-app/search/routes.js
part 2 really.
+ Create shared function "controller"
+ Use shared functions for marketplace, details, and search result page.
No visual change.
=> MUMUP-2199 : Refactor search to search package

angularjs-portal-home/src/main/java/edu/wisc/my/home/api/RestProxyApplicationConfiguration.java, pom.xml
Allows our Rest Proxy to handle wisc.edu/directory, wiscmail, and possibly google searching.
=> Adds a new HttpMessageConverter for Rest Proxy

angularjs-portal-home/src/main/webapp/css/search-results.less, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html, angularjs-portal-home/src/main/webapp/my-app/search/services.js
+ Add in wisc.edu search results (looking at mock data right now
+ Revamp myuw search results to be more specific (variable renames)
+ Shows 1-10 of x with link to wisc.edu of that search. (Keir's suggestion)
Styling based on mockups : https://docs.google.com/presentation/d/18OzygRCY4npTOu_tnBgUogLitto0kjWMRRz1t7Cn8dQ/edit#slide=id.g74158e4a7_0_24
+ Overall
+ View more link
=> MUMUP-2199 : Wisc edu search

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html, angularjs-portal-home/src/main/webapp/my-app/search/services.js
=> MUMUP-2199 : Cleanup some wisc.edu search stuff

angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
=> Javascript math

angularjs-portal-home/src/main/webapp/my-app/layout/spec/layout_controller_spec.js
+ Silent login injection now in place.
Relates to https://github.com/UW-Madison-DoIT/uw-frame/pull/135
=> MUMUP-2356 : Fix unit tests for layout controller

angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
Add in dependency so marketplace dets work. Error looks to be unrelated. Will fix separately.
=> Add in dependency for $routeParams in marketplace details

angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html
Need this first: https://github.com/UW-Madison-DoIT/uw-frame/pull/138 :white_check_mark: 
+ adds background to static
+ adds background to exclusive
before
after
Good catch @Daha5
=> MUMUP-2357 : update to have background style, for the style

angularjs-portal-home/src/main/webapp/css/search-results.less, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Loading state is too fast, but all sections have a loading gif.
=> MUMUP-tbd : Happy loading, Happy no results

angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
=> Forever ALoad

angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Pulling a commit for https://github.com/UW-Madison-DoIT/angularjs-portal/pull/392/ for easy-now merging.
=> Suggest browsing as a recovery from a no-results MyUW search.

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/directives.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html, angularjs-portal-mock-portal/src/main/webapp/web/guest-session.json
+ Add in base url to the real site (for redirect purposes)
+ Add in `Login to use` button everywhere that was the action buttons
+ fix a glitch with mobile action buttons not seen
+ details page gets a login to use button
=> MUMUP-2069 : Guest mode for apps

angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Only change is the launch buttons
=> MUMUP-2332 : Read only mode for search results

angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Loading state and empty state are now fixed for all 3.
=> MUMUP-2385 & MUMUP-2378 : Loading state for search

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html
Adding logic to show "Showing X of Y" on rss items.
=> MUMUP-2345 Show Truncated RSS Feed

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
+ Step 1 to using the `override.js`, changing `app-config.js` to have values (step 2 will be to pull out all angularjs-portal specific values into separate config and stop overwriting `app-config.js`)
+ Change `upBase` to `myuwHome` like what is in frame
=> cleanup from override change and feature change

angularjs-portal-home/src/main/webapp/my-app/layout/list/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
+ Changed the "add to home" to "Browse MyUW" based on suggestion in Jira.
+ Changed fa for add to home to `fa-globe` (I just picked one, if you want something else I'm up for convo. Please verify it exists on font awesome before suggesting)
+ Removed the remove button for apps in compact and expanded
+ Removed the Marketplace light entries
_note this is using mock data, so that is why you see those apps_
=> MUMUP-2423 : GuestMode the home page

angularjs-portal-home/src/main/webapp/js/app-config.js, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html, angularjs-portal-home/src/main/webapp/my-app/search/services.js
Allows for configurable directory searches
No Directory example where section just drops out - 
Someone in the 'UW-Madison' Group via the configuration
=> No directory search for you

README.md
Links the new slide deck as published.
=> Link the newly available MyUW Overview slide deck.

angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html
+ Adds a proper loading state on exclusive
=> MUMUP-2427 : Add in loading state to exclusive mode

angularjs-portal-home/src/main/webapp/css/home.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
+ Renamed class for widget content
+ This also fixes an issue in exclusive mode where portlet-content is the other div in some portlet markup that is sent back.
=> MUMUP-2430 : Fix styling for widget card for static content

angularjs-portal-home/src/main/webapp/WEB-INF/web.xml, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/route.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/routes.js, angularjs-portal-home/src/main/webapp/my-app/main.js
This is the first step in splitting out my-tools home into its own app. This also upgrades widget creator to use the latest widget code. They are one in the same now. So now we can do more than creating custom widgets with widget creator. We can demo some of the templates. Picked a couple high usage ones.
+ Added a `widgetConfig` section for widgets with config
+ Added `widgetURL`, only used by RSS type for now
+ Added RSS, LOL, and Search with links types to widget creator
=> MUMMNG-1734 : Add widget creator to web

angularjs-portal-home/src/main/webapp/my-app/layout/services.js
Server-side error was bypassing client-side failure function. Moved the $http.get(...) function to it's own method, and test the results of that.
=> MUMUP-2431 Trap exclusive mode error and display message.

angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json
Took the liberty and made it dissmissable.  I put a [comment] (https://jira.doit.wisc.edu/jira/browse/MUMMNG-2401?focusedCommentId=669663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-669663)  in the JIRA, won't merge until I hear one way or the other.
=> MUMMNG-2401 Adds WRS Statement notification

docs/markdown/home.md
=> home.md edit pass

angularjs-portal-home/src/main/resources/endpoint.properties.example, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
+ Removed `JSONP` call to Google's feeds service
+ Added `GET` call to rest-proxy (which calls https://rss2json.com/api.json for now, can revamp later)
+ Removes snippet feature (not available in https://rss2json.com/api.json)
+ Adds limit title feature
=> MUMUP-2457 : Remove deprecated Google API

angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
So we can close https://github.com/UW-Madison-DoIT/angularjs-portal/pull/438 and get this merged now rather than later.
=> Open new tab

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html
+ The showing x of y no longer highlights and no pointer
+ Text cleanup in error state
+ Restructured RSS to have 2 divs that are inline-blocks
+ Utilized `a.full-width` to remove awkwardness about inline with block elements inside.
+ Also changed the size of widget creator to match what the real widget widths are
=> MUMUP-2477 : Cleanup rss with new styles

angularjs-portal-home/src/main/resources/endpoint.properties.example, angularjs-portal-home/src/main/webapp/staticFeeds/wiscard.json, angularjs-portal-mock-portal/src/main/webapp/web/marketplace/entries-guest.json, angularjs-portal-mock-portal/src/main/webapp/web/marketplace/entries.json
This configures local angular to work with new wiscard widget supplied here: https://github.com/UW-Madison-DoIT/uPortal/pull/471
=> Wiscard widget

docs/markdown/app-directory.md, docs/markdown/home.md
Document app directory entries.
See [preview of resulting documentation](https://github.com/apetro/angularjs-portal/blob/doc-app-directory/docs/markdown/app-directory.md).
=> App directory documentation.

angularjs-portal-home/src/main/webapp/css/widget.less
=> minor cleanup for rss widget

angularjs-portal-home/src/main/webapp/staticFeeds/features.json
Noticed we didn't upgrade the features feed for ajsp when we added the grouping feature.
=> Add in groups to features feed

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html
=> Check if date is hidden, if so let the title go full width

angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
=> MUMUP-2451 Graceful Exclusive Rendering on Authentication error

angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
=> if you don't have access the meta data, it still says access denied

angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html
=> Actually true is false, and false is true

angularjs-portal-home/src/main/webapp/staticFeeds/features.json
And I will see and it will be good
=> Let There Be Wiscard Widget

angularjs-portal-home/src/main/webapp/staticFeeds/features.json
=> Updates the img url for the wiscard announcement

angularjs-portal-home/src/main/webapp/my-app/layout/list/partials/home-list-view.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
We had a beta feature we wanted to try out a while back with adding a filter to the home page. When we revamped the app menus we never fixed the code so that this beta feature worked. had a free couple minutes so thought I'd fix that.
=> Fixes the beta feature to filter things on your home screen

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html
For LOL, if they don't provide a launch text, it looks weird so lets just hide it.
=> If no launch text, don't show the button

angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json
@keirserrie helped out with the text of the notification.
I'm really looking for the opinion of Will Crickman of linking to kb article : https://kb.wisc.edu/page.php?id=15303.  I'm reaching out to Will offline (I don't think he has a github account).
=> MUMMNG-2547 Notify System users who are ineligible

angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json, angularjs-portal-home/src/main/webapp/staticFeeds/old_notifications.json
\- UW Specific Notifications
\+ Demo Data
UW Specifics will be covered in overlays.
=> replace uw specific notifications with demo data

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html
Clean up some of the onscreen help in widget creator based on feedback from @mrfarnham . Thanks Mike.
=> Widget creator buffering

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
This at least removes the loading gif when you get nothing back (just like in compact mode)
=> MUMUP-2583 : Edge case where you don't have anything in your layout spins forever

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
=> Add in a toast on remove, saying it happened

angularjs-portal-home/src/main/webapp/js/web-config.js
`UW System-Platteville` [seems to be the right group](https://github.com/UW-Madison-DoIT/uw-frame/blob/0dc85d58f1ae6496ae8057ed4ee2c652a72dd33c/uw-frame-components/js/frame-config.js#L264).
=> MUMUP-2612 : set kbSearchUrl for UW-Platteville.

angularjs-portal-home/src/main/resources/endpoint.properties.example, angularjs-portal-home/src/main/webapp/js/web-config.js
+ Adds config to `web-config`
+ Adds key in `endpoint.properties.example` for easy dev
=> MUMUP-2585 : UW Platteville Google Search Config

angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
=> MUMUP-2629 : Use title for public, name is just for admin

angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
+ Load More now only shows if there are entries that are hidden
+ Load More count resets to 20 when you change your filter search item
+ Change [tabs to 2 spaces](https://www.youtube.com/watch?v=cowtgmZuai0), to see just changes [click me](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/497/files?w=1)
=> MUMUP-2632 Fix load more always showing

angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
Per @timlevett [suggestion](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/495/files#r73527582).
=> mv $scope.ratingPrefix declaration into init function().

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
+ Remove toast from compact mode
+ Remove dependency injection of `$mdToast` for both compact and expanded modes
=> MUMUP-2641 : Remove toast from compact mode as well

angularjs-portal-home/src/main/webapp/css/home.less, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
=> Add expanded/compact widget toggle to app-header

angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html, angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/directives.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Removed lingering issue causing nasty grams in the console.
=> Remove reference to partial that no longer exists

angularjs-portal-home/src/main/webapp/main.js
This overrides the base `main.js` in attempt to force a login before the angular modules `my-app` and `portal` are bootstrapped.
=> MUMUP-2671 : Change up bootstrap of angular

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/search-with-links.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Makes it possible to change launch text for any type of widget's launch button. We could further enhance this in the future to be a component, but this works for now.
=> MUMUP-2690 : Make all widgets launch text configurable

angularjs-portal-home/src/main/webapp/js/login-config.js, angularjs-portal-home/src/main/webapp/js/override.js, angularjs-portal-home/src/main/webapp/main.js, docs/markdown/home.md, docs/markdown/silent-login.md
Make the silent login step somewhat skip-able to fix localhost heavy development and fix master.
=> MUMUP-2670 : Cleanup silent login step

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-mock-portal/src/main/webapp/api/layoutDoc
`commit --amend-to #511` (related to #511).
This will make default widgets get the alt launch button text.
=> let normal widget launch button be different text

angularjs-portal-home/src/main/webapp/main.js
Minor bug where portal returns "failed" as the login for the guest user.
=> Fix login if guest (which returns failed from /portal/Login)

angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js
Only see categories for those portlets which a user can add.
=> MUMUP-2684 add filter to categories

docs/markdown/expanded.md, docs/markdown/widget-launch-button.md
Based on the fine work of @jjones770 in https://docs.google.com/document/d/1JQOe0a9XPZdTev-M7qyl_bRHn3acBSVJLkTvx57uIf4/edit
=> MUMUP-2714 : Launch button guidance

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html
In this PR:
- Removed most references to bootstrap in favor of angular material directives
- Some small sizing/spacing adjustments
=> Materialize widget creator

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/staticFeeds/wiscmail-accounts.json
+ If you are on a small screen (material 'xs'), default to compact if you have compact enabled in the config, otherwise default.
+ Updated a mock data object for email so it stopped complaining in the logs.
=> MUMUP-2649 if you are on mobile screen make it compact

.gitignore, build-docs-local.sh, docs/markdown/compact.md, docs/markdown/expanded.md, docs/override.js, package.json, update-docs.sh
+ Make a build script to run local docs `npm run docs`
+ Add build script to just update the content `npm run update-docs`
+ Fix broken img's
+ disable storage, notifications, and features for docs as that is silly.
=> improve ajsp docs

angularjs-portal-home/src/main/webapp/css/general.less, angularjs-portal-home/src/main/webapp/css/home.less, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html, angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html, angularjs-portal-home/src/main/webapp/my-app/search/partials/campus-domain-results.html, angularjs-portal-home/src/main/webapp/my-app/search/partials/directory-results.html, angularjs-portal-home/src/main/webapp/my-app/search/partials/marketplace-results.html
- Added CSS to compensate for styles that were removed from uw-frame in [#339](https://github.com/UW-Madison-DoIT/uw-frame/pull/339)
=> Adjust styles to compensate for uw-frame CSS changes

angularjs-portal-home/src/main/webapp/staticFeeds/features.json
As apart of https://github.com/UW-Madison-DoIT/uw-frame/pull/332
Changing the feature.json file endDate attributes to have a more human-readable date (From epoch to ISO).
=> MUMUP-2716 : Change features.json endDate to human-readable

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html
* Forthright language.
* Don't use "here" link.
* Use safe target=_blank .
=> Tweak Widget Creator documentation link.

angularjs-portal-home/src/main/webapp/css/widget.less, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lti-launch.html, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Adds a new type of widget lti-launch
=> WCP-441 Adds LTI-Launch as a widget type

angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html
=> MUMUP-2819 Fixes links with LOL > 5 links

README.md, angularjs-portal-home/src/main/webapp/js/master-override.js, angularjs-portal-home/src/main/webapp/js/override.js, docs/README.md, docs/app-directory.md, docs/compact.md, docs/expanded.md, docs/search.md, docs/silent-login.md, docs/widget-launch-button.md, docs/widgets.md
+ Fixes broken list styling
+ Normalizes fenced code boxes
+ Normalizes headings
+ Clarifies or eliminates MyUW-specificity
+ Edits for brevity
+ Fixes various typos.
Semantic commits with documenting commit messages.
=> MUMUP-2832 Documentation updates

build-docs-local.sh, docs/build-docs.sh
+ `mvn clean package && mvn jetty:run` still works without the scripts.
+ Found no remaining mentions of the scripts `grep`ping within the project.
=> MUMUP-2827 remove doc-building shell script remnants.

docs/_layouts/default.html
- Fixes octocat image (did search for other images)
- Fixes the return to home link
=> MUMUP-2832 Misc fixing of doc links

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
Weather widget now cycles between Fahrenheit, Celsius, and Kelvin. The user's last choice will persist.
=> AddingKelvin

angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
Fixed initialization error. Defaults to Fahrenheit for new user
=> Weather login

angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entries-guest.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entries.json
=> MUMMNG-2978 add keywords for Grad Student Portal entry

.gitignore, README.md, docs/README.md, docs/apereo-incubation.md
Captures some status and next steps from today's Apereo Incubation initial conference call.
=> Document Apereo Incubation status

.travis.yml, pom.xml
Configure checkstyle with Google code style.
Add checkstyle to Travis CI tests.
=> Issue #582: Add checkstyle to maven build

README.md
Seems that the convention is to have the badges at the top and in lowercase.
=> Move badge and match case convention

angularjs-portal-home/src/main/webapp/js/login-config.js, angularjs-portal-home/src/main/webapp/js/master-override.js, angularjs-portal-home/src/main/webapp/js/override.js, angularjs-portal-home/src/main/webapp/js/web-config.js, angularjs-portal-home/src/main/webapp/main.js, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/list/route.js, angularjs-portal-home/src/main/webapp/my-app/layout/route.js, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/spec/layout_controller_spec.js, angularjs-portal-home/src/main/webapp/my-app/layout/spec/toggle_controller_spec.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/routes.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/widget/routes.js, angularjs-portal-home/src/main/webapp/my-app/main.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/directives.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/routes.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js, angularjs-portal-home/src/main/webapp/my-app/rating/components.js, angularjs-portal-home/src/main/webapp/my-app/rating/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/directives.js, angularjs-portal-home/src/main/webapp/my-app/search/routes.js, angularjs-portal-home/src/main/webapp/my-app/search/services.js
same as #587, but without ES2015+ changes applied, to maintain IE support.
=> Issue #582: Use 'eslint --fix' to apply linter recommendations

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
+ Document requirement in CONTRIBUTING.md.
+ Add ICLA-adherence checkbox to pull request template.
=> Guide Contributors to Apereo ICLA compliance

README.md, docs/apereo-incubation.md
* Adds "uPortal ecosystem incubating" badge.
* Normalizes whitespace for badges in README.md source
* Makes "Apereo incubating" badge consistent between website and README.
----
=> Add uPortal ecosystem incubating badge.

.travis.yml
`npm install` only needs to be run one time.
----
=> Remove duplicated Travis CI install script

package.json
husky installs git hooks, eslint-git-changes automatically sees what files are different between staged files and HEAD, then feeds files to ESLint.
----
=> Before commit automatically lint check updated javascript files

docs/apereo-incubation.md
Proposing project name changes for incubation
----
=> MUMUP-2886 adding name transitions and descriptions

angularjs-portal-home/src/main/webapp/css/widget.less
Adds back in the styling for when one renders a widget in a `focused` mode
----
=> MUMUP-2898 Adds back in widget styling for focused widget

angularjs-portal-home/src/main/webapp/js/master-override.js, angularjs-portal-home/src/main/webapp/js/override.js, angularjs-portal-home/src/main/webapp/js/web-config.js, angularjs-portal-home/src/main/webapp/main.js, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/static/directives.js, angularjs-portal-home/src/main/webapp/my-app/main.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/directives.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js, angularjs-portal-home/src/main/webapp/my-app/rating/components.js, angularjs-portal-home/src/main/webapp/my-app/rating/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/directives.js, angularjs-portal-home/src/main/webapp/my-app/search/services.js, package.json
Fixing John Papa guidelines without angular/controller-as
----
=> Issue #604 John Papa Guidelines

docs/widgets.md
Remove description of unused dateFormat feature and describe other configuration options.
=> Update RSS widget documentation

angularjs-portal-home/src/main/webapp/my-app/layout/partials/portlet-icon.html
Companion to [uw-frame #410](https://github.com/UW-Madison-DoIT/uw-frame/pull/410): Adds mdIcon support for app marketplace results.
=> Portlet icon should prefer mdIcon if available

docs/widget-launch-button.md
To reflect the default behavior expressed in: [uw-frame #411](https://github.com/UW-Madison-DoIT/uw-frame/pull/411)
=> Update launch button default text doc

angularjs-portal-home/src/main/webapp/js/master-override.js, angularjs-portal-home/src/main/webapp/js/override.js, angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html, angularjs-portal-home/src/main/webapp/my-app/layout/partials/remove-button.html, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/CourseGuide-Browse-Courses.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/HRSManagerTimeApproval.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/MyCourses.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/course-services.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/earnings-statement.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/feedback.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/learn-at-uw.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/new-hire-netid-activation.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/student-center.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/university-staff-benefits-statement.json, angularjs-portal-mock-portal/src/main/webapp/api/marketplace/entry/wisc-mail.json, angularjs-portal-mock-portal/src/main/webapp/layout.json
Switching off of layoutDoc because it's been deprecated in uPortal 4.3 and 5.
----
=> MUMMNG-3295 switch to layout.json

appveyor.yml
Automated testing for Windows :checkered_flag: 
To enable continuous windows builds go to https://ci.appveyor.com/projects/new and flip the switch. :zap: :bulb: 
Example output: https://ci.appveyor.com/project/ChristianMurphy/angularjs-portal/build/1.0.1
Related to UW-Madison-DoIT/uw-frame/pull/408
----
=> Run continuous integration on Windows using AppVeyor

README.md
shields.io is used by many projects; this version of the badge is in keeping with the standard look and feel of other badges.
----
=> Switching to shields.io incubating badge with logo

.github/CONTRIBUTING.md
Offering my local crib notes for how to locally build, test, lint for inclusion in `CONTRIBUTING.md`.
----
=> Add contributor guidance re local testing and linting.

angularjs-portal-home/src/main/webapp/js/master-override.js, angularjs-portal-home/src/main/webapp/js/override.js
We were relying on frame to put in the /web for this project.  No more.  
----
=> Copes with frame stopping to rely on /web

docs/apereo-incubation.md
+ Links the slides for tomorrow's bit about incubation status, which should make it easier to navigate to the slides in the moment, and should make them more discoverable.
+ Updates links and labels about incubation status check-ins to reflect held call and scheduled call.
----
=> Link incubation slides

angularjs-portal-home/src/main/webapp/js/override.js
=> Temp change to demo CI

angularjs-portal-home/src/main/webapp/js/override.js
Reverts UW-Madison-DoIT/angularjs-portal#643
=> Revert "Temp change to demo CI"

angularjs-portal-home/src/main/webapp/js/web-config.js
Changes directory search urls to use the aries proxy. Committed in separate commits in case anyone wants to cherry pick.
----
- [x ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> Aries search config

angularjs-portal-home/src/main/webapp/js/web-config.js
Updates Google searches to use aries proxy.
----
- [X ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> Aries google

angularjs-portal-home/src/main/webapp/main.js, angularjs-portal-home/src/main/webapp/my-app/layout/directives.js, angularjs-portal-home/src/main/webapp/my-app/layout/services.js, angularjs-portal-home/src/main/webapp/my-app/layout/spec/layout_controller_spec.js, angularjs-portal-home/src/main/webapp/my-app/layout/spec/toggle_controller_spec.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js, angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js, angularjs-portal-home/src/main/webapp/my-app/rating/components.js, angularjs-portal-home/src/main/webapp/my-app/search/controllers.js, angularjs-portal-home/src/main/webapp/my-app/search/services.js, package.json
Linter will now error if it receives an invalid configuration [[1]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#config-validation), ESLint now is better able to handle comments [[2]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#-ast-nodes-no-longer-have-comment-properties), Spacing rules are now stricter by default [[3]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#indent-rewrite) [[4]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#padded-blocks-defaults) [[5]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#-the-space-before-function-paren-rule-is-more-strict-by-default) [[6]](http://eslint.org/docs/user-guide/migrating-to-4.0.0#-the-no-multi-spaces-rule-is-more-strict-by-default).
----
[Apereo CLA roster]: …
=> Upgrade ESLint to version 4

.github/CONTRIBUTING.md, CODE_OF_CONDUCT.md, docs/apereo-incubation.md
We're an Apereo uPortal ecosystem project. Incubating, even. So now that uPortal acknowledges that the Apereo Welcoming Policy applies, we should too.
----
=> Acknowledge Apereo Welcoming Policy.

docs/apereo-incubation.md
[MyUW service roadmap sets goal](https://docs.google.com/document/d/1yet7w3Nz50gcH19edMCLqCxde0IcQzmVTrZwxj0jzPk/edit#heading=h.netoy48odx97) of legitimately renaming and moving repos this quarter. Updates incubation working doc to reflect this.
----
=> Note progress intended in Q3 2017.

README.md, docs/README.md, docs/apereo-incubation.md
Prefer asynchronous email lists over synchronous chat.
Don't set the unsustainable expectation that team members are available in real time.
----
=> rm Gitter.im mentions; emphasize uportal-user@ email list instead.

SUPPORT.md
Direct people towards asking questions on the uPortal mailing list.
Adapted from the Angular support file. https://github.com/angular/angular-cli/pull/7082
See https://github.com/blog/2400-support-file-support for github support.
----
=> docs(github): Add SUPPORT.md to guide questions to the mailing list

docs/apereo-incubation.md
Updates the incubation status working document in the product documentation to 
+ reflect latest progress
+ better articulate some status and next actions, and
+ better summarize status vs exit criteria.
This will support updating the official incubation record as well as sets the stage for noting continued incubation status in the working document.
----
=> Reflect latest incubation status

docs/README.md, docs/presentations.md, docs/screenshots.md
Make it easier to understand uPortal-home by linking relevant presentations and screenshots.
----
=> Link screenshots and presentations

docs/apereo-incubation.md
Link to Apereo's official version of the incubation record.
----
=> Hyperlink formal incubation record.

docs/apereo-incubation.md
=> Note next scheduled Incubation check-in call.

CHANGELOG.md
resolves build conflict between #671 and #672
:art: Angle braces are recommended so links can be identified by [CommonMark spec](http://spec.commonmark.org/0.28/#autolinks) compliant parsers.
----
=> style(changelog): wrap literal link in angle brackets

README.md
Helps communicate the projects ideal of cross platform support.
----
=> docs(readme): add badge for AppVeyor, Windows continuous integration

.github/CONTRIBUTING.md
Document in contributing guidance to use Conventional Commits, while emphasizing that contributing guidance is not intended to be an insurmountable barrier to contribution.
----
=> Document adoption of Conventional Commits.

angularjs-portal-home/src/main/webapp/js/web-config.js
Removing google search due to api being disabled. This will remove the configuration in the base project, but I'll probably use tier configuration to migrate this change quicker.
----
=> fix(search): remove google search configuration

angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js, angularjs-portal-home/src/main/webapp/my-app/layout/services.js
Fix to remove linting errors
----
- [ X] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
=> fix: Remove linting errors

angularjs-portal-home/pom.xml
=> build: update to latest app-frame

.github/CONTRIBUTING.md, CHANGELOG.md, README.md, committers.md, docs/README.md, docs/apereo-incubation.md, docs/contributors.md, docs/releasing.md, package.json, pom.xml, web/pom.xml, web/src/main/webapp/js/README.md
purging references to angularjs-portal. Except for the references that reference the purge.
----
=> docs: update references to github repos

.github/CONTRIBUTING.md, docs/presentations.md
It turns out there's a [MyUW Examples slide deck](https://go.wisc.edu/myuw-examples). Link it from the page collecting links to presentations related to uPortal-home.
----
=> Link MyUW examples deck

README.md
=> docs(readme): update appveyor badge

package-lock.json, package.json
=> chore(package): update eslint-plugin-compat to version 2.0.1

CHANGELOG.md
=> Catch up CHANGELOG.md to current

web/src/main/webapp/js/override.js
- Implement [simple version](http://uportal-project.github.io/uportal-app-framework/configurable-menu.html) of app navigation added in [uportal-app-framework #561](https://github.com/uPortal-Project/uportal-app-framework/pull/561)
----
=> feat: Add app navigation items

web/pom.xml
Use latest snapshot 6.1.1-SNAPSHOT
----
=> chore: Update app-framework to latest snapshot

web/src/main/webapp/my-app/marketplace/controllers.js
Rescopes session variable, fixes code style issue
----
=> MUMUP-3107

web/src/main/webapp/my-app/marketplace/controllers.js
Style marketplace controller code to adhere to style guide.  Fixes CI builds
----
=> style(lint): Style code to follow style guide

CHANGELOG.md
Updates changelog to reflect changes since most recent release, predicting that next release will be `7.1.0` since new features (but I hope not breaking changes) are included.
----
=> chore(changelog): Catch up pending change towards 7.1.0

web/src/main/webapp/css/marketplace.less, web/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html, web/src/main/webapp/my-app/marketplace/partials/marketplace.html
#739 caused a bug (due to controller scope) that caused some functions of the marketplace page to break, as well as a bug in the appearance.
- Made `<frame-page>` the outermost element to ensure correct layout
- Switched binding of MarketplaceController to be on an element within the `<frame-page>`
- In #739, the frame-page was contained in a div element that was left in place because it had an angular controller bound to it. This caused visual bugs as well as problems in that same controller. To fix this, we just had to remove that div and bind the controller to a separate container div within the frame-page.
- Switched text filter bar to use material icon
- Changed text filter placeholder text to communicate that it's a *filter* (not a search)
- Removed unused bootstrap …
=> fix: enable text filter on marketplace

web/src/main/webapp/css/marketplace.less
- Updates marketplace details page to work with the new flex-based layout using plain CSS instead of messing with DOM structure (to demonstrate another upgrade path)
----
=> fix: make details page conform to new structure

CHANGELOG.md
Updates changelog to reflect 7.1.0
----
=> chore: update changelog to reflect 7.1.0 release

docs/apereo-incubation.md
The September call is no longer the next call, it happened, with an audio recording. Today's call is now the next call.
----
=> docs(incubation): link 2017-09-20 audio and 2018-02-19 agenda

docs/apereo-incubation.md
Takes a pass through the outline of status against Incubation criteria, 
+ Noting a couple items are not fulfilled
+ Noting action items open for some
+ In general updating to reflect current reality.
----
=> Update incubation status outline to reflect current

README.md
Let's stop misleading about the ease of integrating with the Notifications Portlet.
----
=> docs: rm untrue assertion that reads notifications from portlet

docs/apereo-incubation.md
+ link audio recording of call
+ note quantity of participants including newly discovered adoption
+ normalize whitespace in documentation re incubation
----
=> docs: followup on 2018-02-19 incubation status call

docs/apereo-incubation.md, docs/roadmap.md
Initial stab at articulating bigger picture product roadmap.
----
=> docs: articulate product roadmap

CHANGELOG.md, package-lock.json, package.json
=> chore(package): update stylelint to version 9.1.3

CHANGELOG.md
=> docs: add v8.0.0 to CHANGELOG

.gitignore
Exclude local Visual Studio Code configuration from source control.
----
=> fix: add .vscode to .gitignore

package-lock.json, web/src/main/webapp/my-app/layout/controllers.js, web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
Drag and drop doesn't work at the moment, adding move with drag function
----
=> fix: add reorder logic to drag event

CHANGELOG.md, web/src/main/webapp/WEB-INF/web.xml, web/src/main/webapp/js/override.js, web/src/main/webapp/my-app/main.js, web/src/main/webapp/my-app/menu/partials/app-menu-template.html
- Added side navigation link to "version info" page (containing former content of "About" page)
- Updated "About" page to include info about MyUW
- Removed unused side navigation link to "New Features" page
**Companion merge request:** [uportal-app-framework#758](https://github.com/uPortal-Project/uportal-app-framework/pull/758)
----
=> feat: Add new version info page

CHANGELOG.md
CHANGELOG hadn't been updated to reflect that `8.1.2` release happened with what changes. This changeset updates the CHANGELOG to reflect that release.
----
=> docs(changelog): reflect 8.1.2

README.md
Modest copy edit and style pass on README.md .
Most substantive change is a new "What is this?" statement.
=> docs(readme): style and copy edit pass

web/src/main/webapp/my-app/marketplace/controllers.js
=> Replace GuestMode

web/src/main/webapp/main.js, web/src/main/webapp/my-app/search/controllers.js
removes rootScope guestMode
----
=> fix: removes rootScope guest mode

CHANGELOG.md
=> docs: update CHANGELOG to 8.3.1

package-lock.json, package.json
Resolves #849 
Makes it clear that package.json cannot and will not be released.
https://docs.npmjs.com/files/package.json#private
----
=> fix: make package private

CHANGELOG.md
=> docs: update changelog to 8.3.6

web/src/main/webapp/my-app/main.js
continuation of https://github.com/uPortal-Project/uportal-app-framework/pull/878
----
=> fix: remove features route

CHANGELOG.md
Changelog updates to reflect the forthcoming 9.0.0 release.
----
=> docs(changelog): note 9.0.0 release

web/src/main/webapp/my-app/marketplace/partials/marketplace.html
Removed word "most" from "Most popular" column header so as to accurately reflect how we feel about the data contained thereunder.
----
=> MUMUP-3344 Not most popular Just popular

CHANGELOG.md
Intend to cut a 9.1.0 release presently, this updates the changelog to reflect.
----
=> prepare changelog for 9.1.0 release

web/src/main/webapp/my-app/search/partials/search-results.html
* fix: allows suppressed widget containers to collapse to nothing, rather than leaving weird gaps on page
* fix: removes duplicate search tool entry
* adds a couple more search tools
* contextualizes with intro text and welcomes suggestions
----
=> Improve search "other" tab

CHANGELOG.md
=> Update changelog to include 16.0.2 uportal-app-framework release

web/pom.xml
With the release of uPortal-app-framework 17.0.0, 17.0.1-SNAPSHOT is the new latest snapshot.
----
=> overlay upon latest framework: 17.0.1-SNAPSHOT

CHANGELOG.md
Clarify in CHANGELOG the relationship between the versions there and those published to Sonatype.
----
=> clarify that the versions being logged are those published to Sonatype

web/pom.xml
Use uportal-app-framework 17.0.4-SNAPSHOT----
=> Use uportal-app-framework 17.0.4-SNAPSHOT

CHANGELOG.md
Reflect recent releases in the change log.
=> catch up changelog to 10.3.2

CHANGELOG.md, web/pom.xml
=> Use v18.1.1-SNAPSHOT of uportal-app-framework

CHANGELOG.md, web/src/main/webapp/my-app/layout/services.js, web/src/main/webapp/my-app/marketplace/services.js, web/src/main/webapp/my-app/search/services.js
=> Configure $http.get usages to cache

CHANGELOG.md
=> Changelog update to include uportal-app-framework 19.0.2 release

web/src/main/webapp/js/override.js, web/src/main/webapp/my-app/layout/controllers.js, web/src/main/webapp/my-app/layout/list/partials/home-list-view.html, web/src/main/webapp/my-app/layout/services.js, web/src/main/webapp/my-app/layout/static/controllers.js, web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html, web/src/main/webapp/my-app/marketplace/controllers.js, web/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html, web/src/main/webapp/my-app/marketplace/services.js
**Updated functionality:**
- Read/load layout
- Add a widget to home
- Remove widget from home
- Drag and drop / move widgets using mouse
- Ensure check icons are in sync with hasInLayout
- Fix compact cards display
- Mobile display and functionality
- Move widget on key-press ($scope.moveWithKeyboard)
**To do:**
- Remove hardcoded API references before merging
**Feature flag:**
- Created two new feature flags in override.js (useNewLayout & useOldLayout)
----
=> WIP: service layout replacement

CHANGELOG.md, web/src/main/webapp/my-app/layout/services.js
Checking for duplicate elements in data.layout array, filtering duplicate elements out, and saving filtered array as a `filteredDataLayout`.
----
=> Ensure there are no duplicate fnames in dataLayout

CHANGELOG.md
=> Changelog update for uPortal-app-framework 21.0.4 release
