- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-frame/src/main/webapp/partials/header.html
- angularjs-portal-home/src/main/webapp/js/angular-page.js
- angularjs-portal-home/src/main/webapp/js/notifications/notification-controllers.js
- angularjs-portal-home/src/main/webapp/partials/layout.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
Remember that one time we had downtime and we started working on notifications, but then hid it because it wasn't ready for beta 1?  Lets un-hide this work with a beta flag.
> LUNCH : bring back notification demo in beta settings

- angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
- angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less
- angularjs-portal-frame/src/main/webapp/css/buckyless/sidebar.less
- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-frame/src/main/webapp/partials/header.html
- angularjs-portal-frame/src/main/webapp/partials/sidebar-left.html
- angularjs-portal-frame/src/main/webapp/partials/username.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
So, I don't like doing things twice. So given the choices in the JIRA for MUMUP-1437 between fixing the long name in the header and then redoing that fix again if/when we put it in the sidebar, I propose we just put it in the sidebar AND put in a small profile picture like we've talked about in the past.
Here's how it would look:
Until we get the back-end in place to allow actual profile pics uploaded by users (if that's something we want to do), we could just put in a placeholder image or Bucky, like so:
And, this fixes the name issue, even for atypically long names :)
> MUMUP-1437: Prof pic to fix long name

- angularjs-portal-home/src/main/webapp/partials/settings.html
Gather the Beta Settings regarding profile picture together.  Set whether to show the profile pic and what profile pic to show near one another in the settings UI.
Before:
After:
> Gather the profile-pic-related settings together.

- build.sh
to avoid stealing focus under MacOS.
> Set -Djava.awt.headless=true on mvn invocations

- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-home/src/main/webapp/partials/layout.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
Adds a Beta setting for turning on using the static content card template rather than the default card template for portlets with associated static content.
> MUMUP-1379 Add Beta setting for using static content card template.

- angularjs-portal-frame/src/main/webapp/css/angular.less
Not sure we need Bootstrap in Bower, now that UW UI Toolkit includes it. But leaving there for now.
> Use UW-UI-Toolkit in /web, including Bootstrap

- angularjs-portal-frame/src/main/webapp/js/main/main-service.js
- angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js
[MUMUP-1500](https://jira.doit.wisc.edu/jira/browse/MUMUP-1500).
Without this change, when you
1) Log in and exercise `/web/apps` as `staff`
2) Log out
3) Log in and exercise `/web/apps` as `admin`
`admin` sees only the Marketplace data visible to `staff` because from the browser's perspective it's the same local browsing session and so `sessionStorage` persisted across these logins.
With this change, when you do those steps, `admin` gets a fresh load of Marketplace data into `sessionStorage`.
This isn't really a security fix, since sharing browser sessions breaks the security model of the Internet, really, and there's only so much as can do about that, but this is really a functionality fix, in that users getting cached Marketplace data that isn't tailored to them was some kind of bug. …
> MUMUP-1500 Only use sessionStorage Marketplace data from same portal session

- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js
- angularjs-portal-home/src/main/webapp/partials/layout.html
- angularjs-portal-home/src/main/webapp/partials/pithy-content-card.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
[MUMUP-1379](https://jira.doit.wisc.edu/jira/browse/MUMUP-1379).
Replaces #98, this time retaining the parallel static content feature that was restored to service in #99.
Adds `pithy-content-card` feature parallel to `static-content-card`.  Pithy cards display pithy content, which is per-portlet markup right on the face of the card.
Adds the feature to the Beta settings.
The Static cards feature takes precedence over the Pithy cards feature, and the Beta settings tells you so when it matters.
> MUMUP-1379 Show pithy content on home (take 2)

- angularjs-portal-frame/src/main/webapp/js/filters.js
Adds a `to_trusted` filter which makes it (dangerously) easy to mark content as "trusted" from AngularJS's perspective.
Here's how you'd use this in say the `pithy-card.html` template so that the HTML from the entity files can include `JavaScript`.
```
<div ng-bind-html="portlet.pithyStaticContent | to_trusted"></div>
```
Without piping through `to_trusted`, the pithy content can only be static `HTML` that doesn't include `JavaScript`.  Safety.
> Add `to_trusted` filter.

- angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
https://jira.doit.wisc.edu/jira/browse/MUMUP-1424
The MyUW Beta link on the top left that takes the user to the MyUW Home was underlining, so I disabled that under every condition and now the link should never underline.
Before (link underlined):
After (link not underlined):
> MUMUP-1424 : Bug: MyUW title underlining

- build.sh
You can now do `./build.sh` just like before that calls `mvn clean package` OR you can now pass in what build steps you want it to do, for example `./build.sh clean install` will call `mvn clean install`.
I also added in notifications for mac and linux. The idea spawned from @apetro 's pull #97.
> Add optional parameters to build and add in mac/linux notifications

- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-home/src/main/webapp/js/angular-page.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js
- angularjs-portal-home/src/main/webapp/partials/layout.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
- angularjs-portal-home/src/main/webapp/partials/static-content-card-max.html
- angularjs-portal-home/src/main/webapp/partials/static-content-max.html
In chats with the team we thought it would be an interesting idea to have static content on an angular page (I think we can credit @vertein with the original idea). This is a beta-setting level view on that.
Please note this takes precedence over both static content on home and pithy content.
When you click on a card when new setting is enabled you are redirected to `/web/#/static/:fname`. This then loads another view.
+ This feature saves a server hit and 2 xslt transformations
+ The only real difference the user will see is speed improvement
+ #incrementalImprovement
> Static content max angular view

- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-services.js
- angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js
- angularjs-portal-home/src/main/webapp/partials/static-content-card-max.html
- angularjs-portal-home/src/main/webapp/partials/static-content-max.html
+ No more server side hit on max static content load, for the most part
+ If you do a deep link to that portlet and a) its not in the shared service or b) another portlet is in the shared service, it then goes to the layout to get it. If the layout doesn't exist yet it calls the service to populate the layout.
+ Moved layout to `$rootScope` so we can reuse it if we stay on `/web`. Note that if you add a portlet to your favs from marketplace it clears the `$rootScope.layout` due to the change.
+ If the portlet is not in your layout we redirect to /web (could be better, could goto marketplace entry (/web/#/app/details/:fname), but that page looked a little broken, buttons didn't do actions, so I didn't do that. Another thought I had was adding fname to the search, then grabbing that and …
> Make the new simple content on angular faster by removing server side hit

- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-services.js
- angularjs-portal-home/src/main/webapp/partials/layout.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
+ Removes beta setting for static content (both versions)
+ Adds in check for alternative max link
+ Swaps out "get full layout, loop through and pray it finds the portlet in your layout" with "get portlet" API call. If you don't have access or gave a bogus fname it redirects to home.
+ Restructured layout.html. We now have 3 states: `NORMAL`, `STATIC`, `PITHY`
`NORMAL` = no static content, or alt max URL was utilized
`STATIC` = static content exists, no max URL
`PITHY` = pithy flag set, has pithy content (*note:* this one trumps `NORMAL` and `STATIC`)
> MUMUP-1537 : Make simple content real

- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js
- angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
- angularjs-portal-home/src/main/webapp/partials/settings.html
+ In beta settings
+ Clicking link will do the search
+ Sorted alphabetically (case insensitive)
Minor changes
+ Moved the ng-repeats to the li instead of the ul for all of the details sections. We don't need a new ul for every item :)
+ removed $scope.$storage (which was pointing at session storage) in marketplaceController as it wasn't being used and conflicted with mainControllers $scope.$storage which was pointing at local storage
> MUMUP-1565 : Admins can now see keywords if they flip the switch

- angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
- angularjs-portal-frame/src/main/webapp/frame.html
- angularjs-portal-frame/src/main/webapp/js/angular-page.js
- angularjs-portal-frame/src/main/webapp/js/main/main-controllers.js
- angularjs-portal-frame/src/main/webapp/js/main/main-directives.js
- angularjs-portal-frame/src/main/webapp/js/main/main-service.js
- angularjs-portal-frame/src/main/webapp/js/main/search-controller.js
- angularjs-portal-frame/src/main/webapp/js/services.js
- angularjs-portal-frame/src/main/webapp/partials/search.html
- angularjs-portal-home/src/main/webapp/home.html
- angularjs-portal-home/src/main/webapp/js/angular-page.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-services.js
- angularjs-portal-home/src/main/webapp/js/main/search-controller.js
- angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-controller.js
- angularjs-portal-home/src/main/webapp/js/marketplace/marketplace-service.js
- angularjs-portal-home/src/main/webapp/partials/settings.html
This has all the work from #119 (many thanks @jhelmer-unicon ) plus some additional re-factoring.
Add typeahead to the searchbox.   
Screens:
+ Restructured search to be in the marketplace code base, and in home module, for the most part
+ Created a stub search controller for frame so adopters have somewhere to start with
+ Moved the session storage caching for marketplace to the service layer (mimic of what was done in layout)
+ Fixed some minor bugs with on submit
+ Made the fetch of the marketplace only happen if the beta flag is set to true.
+ When you select a typeahead item, it just goes to marketplace entry. (what it should do it TBD)
+ When you select a typeahead item, the focus is not correct when you hit the marketplace (this doesn't happen all the time, but sometimes)
+ …
> MUMUP-1079 : Typeahead to search beta feature

- angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts.json
Adds in sample json feed so front end is unblocked waiting for server side on wiscmail accounts
```json
{"accounts" :  
{
"system" : "wiscmail",
"uri"    : "https://wiscmail.wisc.edu",
"linked" : [
{
"sample-link@doit.wisc.edu" {
"system" : "office365",
"uri" : "https://wiscmail.wisc.edu"
}
}
]
}
}
```
> MUMUP-1676 : Create sample json feed

- angularjs-portal-frame/src/main/webapp/partials/header.html
The previous iteration had an absolute (MUM deployment specific) URL for the crest image. Changed to a relative URL available in the build result.
Allows downstream consumers of angularjs-portal-frame to use this
partial unmodified.
> Replace absolute url to crest image with relative path

- angularjs-portal-frame/src/main/webapp/js/directives.js
- angularjs-portal-frame/src/main/webapp/partials/portlet-header.html
Allows app developers to optionally render the title using the
portlet-header style.
Example:
```
<portlet-header app-title="My App Title" app-image="img/square.jpg" app-description="Optional app description."></portlet-header>
```
> Add a <portlet-header> element directive

- angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less
- angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
Previously, screenshots were really tiny and users had no ability to enlarge them or really understand what content the portlet has to offer by seeing the screenshots. I used a bunch of CSS to make them a little bigger, added a border, and also added a hover feature that makes a larger version of the image pop out so the user can get a good glimpse of the content in this portlet.
Before:
After (with larger images in background + hover-enlarge ability):
After (with smaller window):
After (with smaller window and hover-enlarging)
The bigger image disappears as soon as the mouse hovers off of it. 
Also, for those wondering, having the @media only screen several different times was the very inefficient way of keeping the enlarged images from being cut off, but it works very well.
Please note …
> MUMUP-1470: Bigger Screenshots

- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-services.js
- angularjs-portal-home/src/main/webapp/partials/widget-card.html
- angularjs-portal-home/src/main/webapp/partials/widgets/option-link.html
- angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts-1.json
- angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts.json
I know, TL;DR. I would like to have 2x :+1: for this at least. Maybe a post-standup chat.
Single Account
Multiple Accounts
Side by Side
+ Creates a `option-link` widget (idea behind it is one that has a select, and that changes the url for the link)
+ Creates a way of calling the widget URL when the widget mode is loaded (got it working, could be a little better)
+ Plugs in data when we get it
+ Adds in a `WIDGET` flag for generic widgets that will display content from callback (this could be better, but it's a start)
+ Adds in a `OPTION_LINK` flag that will use the option link partial (email will be one of those for now)
+ On selection of the option it will update the URL
+ The promise to get the widget content is doing data.result, another email JSON specific thing
+ I'm not a huge fan …
> MUMUP-1615 : Mail widget for realz

- angularjs-portal-frame/src/main/webapp/frame.html
- angularjs-portal-frame/src/main/webapp/js/angular-page.js
- angularjs-portal-frame/src/main/webapp/my-app.js
This change set includes 2 important changes:
1. The 'app' variable provided by angular-page.js is no longer hidden
from global scope. This will allow "Apps" that overlay
angularjs-portal-frame to have access to the result of angular.module.
2. Adds 'my-app.js' to frame.html. The file included in this project is
intentionally blank. It's inclusion allows an "App" developer an
extension point; the end result is that the downstream app does not have
to have a copy of frame.html, they can just write their own my-app.js.
> MUMUP-1704 : Support "App" model

- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-directives.js
- angularjs-portal-home/src/main/webapp/partials/widget-card.html
- angularjs-portal-home/src/main/webapp/partials/widgets/option-link.html
+ This will make `option-link` 100% reusable
+ Adds in a config object that is needed to configure where to get the JSON
```json
{
"value" : "uri", 
"display" : "email", 
"arrayName" : "linked", 
"singleElement" : true
}
```
+ Has defaults if someone doesn't want to supply config
+ Refactors to a controller instead of a link function for the directive
> MUMUP-1615 : Create configuration for widgets

- angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less
- angularjs-portal-home/src/main/webapp/partials/widgets/weather.html
Reorganized the content and styles of @timlevett's first pass of the Weather widget. Getting it ready for primetime!
- Removed the min/max view in favor of showing everything at once. Less clicks = happier users, and I don't think it looks too messy
- Still using old icons. If we want to switch icons we can do that in a separate pull, but with the new styling it doesn't seem as necessary
- Clicking a city goes straight to the World Weather Online website for that city. Pretty cool.
- Styles consistent with other widgets
Click on Madison:
Go to World Weather Online's beautiful website:
> Make weather pretty

- angularjs-portal-frame/src/main/webapp/css/buckyless/notifications.less
- angularjs-portal-home/src/main/webapp/samples/new-stuff.json
This was the easiest fix. If you have other ideas for how to display the new stuff are, let me know.
Also, since us developers are going to see this forever and some of us are OCD, I fixed the New New annoyingness :)
> Fix styling on new-stuff bar

- angularjs-portal-frame/src/main/webapp/css/buckyless/general.less
- angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less
- angularjs-portal-home/src/main/webapp/partials/marketplace-portlet.html
- angularjs-portal-home/src/main/webapp/partials/portlet-icon.html
+ Add in fa-star (i know, not finalized, but hey thought its easy enough to change)
+ Changed the marketplace to utilize the `<portlet-icon>` directive, removed circle over all the icons
+ Fixed minor styling on mobile so the ratings line up better
> MUMUP-1578 : Default fa icon & lil cleanup

- angularjs-portal-home/src/main/webapp/home.html
- angularjs-portal-home/src/main/webapp/partials/marketplace-light.html
This was a bug where when the user would be scrolled down on their home page and click on the add to favorites (tile), then they would be taken to the marketplace but the scroll would not reset, and thus they'd be left in the middle of the page. 
Here are some screenshots from the JIRA story to help you understand the problem.
User scrolls down and decides to click on Add to favorites
Immediately after clicking the user sees this, instead of being taken to the top of the marketplace.
Anyways, I added some javascript that scrolls up whenever the button is clicked
Now it looks like this:
Before clicking:
After clicking:
> MUMUP-1729 : Bug : Stays scrolled down from bottom of favorites to somewhere in /apps

- angularjs-portal-frame/src/main/webapp/js/directives.js
- angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js
- angularjs-portal-home/src/main/webapp/js/layout/widget-controllers.js
- angularjs-portal-home/src/main/webapp/partials/widget-card.html
This creates a mechanism that we can supply a JSON URL, and a template in the config, and we get smart widgets.
I have one example out of the box solution: 
```xml
<portlet-preference>
<name>widgetURL</name>
<value>/portal/p/earnings-statement/max/earningStatements.resource.uP</value>
</portlet-preference>
<portlet-preference>
<name>widgetType</name>
<value>generic</value>
</portlet-preference>
<portlet-preference>
<name>widgetConfig</name>
<value><![CDATA[{"template" : "<table class='table table-striped'><tr><th>Paid</th><th>Earned</th></tr><tr ng-repeat=\"item in content.report |orderBy: ['-paid.substring(6)','-paid.substring(0,2)','-paid.substring(3,5)'] | limitTo:3\"><td><a href='/portal/p/earnings-statement/max/earning_statement.pdf.resource.uP?pP_docId={{item.docId}}' …
```
> MUMUP-1751 : Create template-able widgets

- angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less
Marketplace entries are no longer clickable, so we should probably stop using the pointer on hover.
> minor style change to make marketplace entries stop giving the pointer for no reason

- angularjs-portal-home/src/main/webapp/partials/portlet-icon.html
To get the conversation started on how we want to handle this.
This has the advantage that this is 100% backwards compatible.  Merging this won't break anything or require us to go back and change entity files.
Disadvantage is that we're checking 'index of' twice for every portlet and the variable name faIcon hanging around.  We would also have to take a look and maybe do some more stylings.  Noticed that the font-awesome and glyphicons are slightly different sizes.
See this branch where I changed the icon to a glyphicon: 
https://github.com/UW-Madison-DoIT/uPortal/tree/glyphicons
> Use an icon for widgets, just not font-awesome

- angularjs-portal-frame/src/main/webapp/css/buckyless/home.less
- angularjs-portal-frame/src/main/webapp/css/buckyless/myuw-toolkit-temporary.less
- angularjs-portal-frame/src/main/webapp/css/buckyless/portlet-frame.less
- angularjs-portal-home/src/main/webapp/partials/default-card.html
- angularjs-portal-home/src/main/webapp/partials/example-widgets.html
- angularjs-portal-home/src/main/webapp/partials/home-header.html
- angularjs-portal-home/src/main/webapp/partials/home-widget-view.html
- angularjs-portal-home/src/main/webapp/partials/static-content-card.html
- angularjs-portal-home/src/main/webapp/partials/widget-card.html
`.widget-content` -> `.widget-frame`
`.card-remove` -> `.widget-remove`
`.card-info` -> `.widget-info`
> Rename some classes to be more semantic and follow Style Guide

- .gitignore
- angularjs-portal-frame/src/main/webapp/bower.json
- angularjs-portal-frame/src/main/webapp/bower_components/requirejs/.bower.json
- angularjs-portal-frame/src/main/webapp/bower_components/requirejs/README.md
- angularjs-portal-frame/src/main/webapp/bower_components/requirejs/bower.json
- angularjs-portal-frame/src/main/webapp/bower_components/requirejs/require.js
- angularjs-portal-frame/src/main/webapp/frame.html
- angularjs-portal-frame/src/main/webapp/main.js
- angularjs-portal-frame/src/main/webapp/my-app.js
With all the scripts included in frame.html, it is easy to overlay the single my-app.js file, but hard to accommodate a modular app with many js files.
With this change, a downstream application can use require to pull in their own dependencies within their overlaid my-app.js (which is now a require module).  Angular will initialize only afterward (this is in lieu of the ng-app directive).
If this works well, a good next step would be to isolate the rest of the javascript resources behind require, so that the frame and app can be organized into their own modules with no risk of interfering with each other through the global namespace.
> Use RequireJS to make my-app more extensible

- angularjs-portal-frame/pom.xml
Reverting part of what https://github.com/UW-Madison-DoIT/angularjs-portal/pull/188 did to get `/frame` up and running again.
> Fix frame: Add back in jstl

- angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less
This pull request fixes the problem with screenshots not re-sizing in Firefox. I set the width for the default screenshots to 100% and whenever the window is >= 768 pixels the width of the default screenshots automatically changes to 320px (so they don't get too big for desktop windows). Also I set the width of the enlarged screenshots to 100% so that it doesn't get affected by the width change to 320px.
Before and After:                                                                                                                                               
Also, because users cannot get an enlarged version of the screenshots when their devices width is below 768px, I had the default screenshots width set to 100% only under that scenario (width<768px), so that tablet /mobile users …
> MUMPO-433: Screenshots don't resize if user is not in chrome

- angularjs-portal-home/src/main/webapp/partials/widget-card.html
In the case of `WIDGET` type widgets, sentence-case the "Launch full app" call-to-action.
> MUMMNG-1305 : trivial : Sentence-case `Launch full app` call-to-action, WIDGET case.

- angularjs-portal-frame/src/main/webapp/css/buckyless/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
This pull request is in regards to error handling for the weather widget under two scenarios: 1st, that the user actually has locations selected in their weather portlet settings, otherwise a frowny face and fix-instructions appear, and 2nd that when the World Weather Online service fails for whatever reason, the user will be gracefully told to click on the link provided to view the local weather (from a different weather service).
Due to the Weather app not actually loading weather on local host, I wasn't exactly able to test my changes under the condition that the back-end services actually work, and so I was hoping to do that on my-test once/if this gets merged. That is, of course, if everything here looks good to you guys.
Screenshots of what i would eventually look like (once …
> MUMUP-1757 : Weather app error handling

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
I cut down the error messages to 1 exclamation point per message (as requested by Phyllis).
When no locations are set:
"Hold up! You haven't set any weather locations yet. Launch the full app to select your weather locations."
When backend service fails:
"Oops! The weather service seems to be down. Try clicking here for Madison weather."
> MUMMNG-1395: Reign in exclamation points in the  Weather Widget

- angularjs-portal-frame/src/main/webapp/css/buckyless/marketplace.less
Phyllis pointed out in the sprint review that for apps without a category, the Details link overlaps the bottom border. After fixing this I couldn't find an example in production so I don't think this is actually an issue...but now it's fixed just in case :)
Localhost before:
After:
> Fix details link overlap

- angularjs-portal-frame/src/main/webapp/css/buckyless/home.less
- angularjs-portal-frame/src/main/webapp/frame.jsp
So Angular straight up doesn't support IE 8, but I don't think our experience on IE 9 is that great either. Do we want to support IE 9 or leave it in the dust? Right now I have it not supported, but it's easy to change it to support IE9.
This code will display a simple div at the top of the page informing users browsing on < IE 10 that they are using an outdated browser and they should update it. This snippet is commonly used on many other websites and links to a site called Browse Happy that shows users how to download a better, up-to-date browser. Personally, I think this would be more engaging and intuitive than linking to a KB doc, but I understand if we want to be more UW-specific with this and go that route instead. Thoughts?
Screenshot of how IE8 would look (I don't have an easy …
> MUMUP-1428: Error experience for <IE10 users

- angularjs-portal-frame/src/main/webapp/css/buckyless/responsive.less
- angularjs-portal-frame/src/main/webapp/portal/main/controllers.js
- angularjs-portal-frame/src/main/webapp/portal/settings/partials/settings.html
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-toggle.html
+ Adds in beta flag to show toggle for widget on mobile (or not)
+ Removed + as it was supposed to be on mobile. There is no `hide-mobile` class :)
> EC : Add in beta flag to show toggle on mobile.

- angularjs-portal-frame/src/main/webapp/main.js
`ui-bootstrap.js` references a bunch of html templates, but does not define them.  So, for instance, you'd get a 404 on "templates/accordion/accordion.html".  The cryptically named `ui-bootstrap-tpls.js` is the one to use, because it includes the templates.
I also noticed the file had CRLF line endings (my bad) so I replaced them with LF.
> Use correct artifact for ui-bootstrap

- angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
This doesn't completely fix the issue - it's still off by a pixel at other zooms, but it fixes it for 100% zoom, which is what most people will be using.
It's a bug with Bootstrap, which is also a tad wonky at different zooms.
MyUW, 100% Before:
MyUW, 100% After:
MyUW, 110% After:
Bootstrap, 110%:
> Fix search bar pixel

- angularjs-portal-frame/src/main/webapp/portal/misc/filters.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html
- angularjs-portal-home/src/main/webapp/samples/wiscmail-accounts.json
* Added in the loading-gif icon while it loads, and centered said gif.
* Added in a `trimMiddle` filter that cuts out the middle of the string, adds in ` ... ` in the middle
* Added filter to option-link filter, with max length 26
* Added title if filter is in effect on the option to show the full text
_I was having issues getting the title to capture, but trust me, its there on hover of an option_
> MUMUP-1904 : Clean up email-widget

- angularjs-portal-frame/src/main/webapp/css/buckyless/header.less
_Please note that this doesn't actually change the name, just lets frame apps have the ability to be more wordy in there title._
> MUMUP-1876 : Fix style so that you can have longer than normal app names

- README.md
If you don't provide an `endpoint.properties`, the `/web` war file will not Spring applicationContext init, and so fails to come up under e.g. `jetty:run`.
This PR updates `README.md` to document that one needs to do this before building.
Went for documentation of the step rather than just going ahead and providing an empty `endpoint.properties`, since a `.gitignore` had carefully excluded `endpoint.properties`.
> MUMUP-1930 update README re providing endpoint.properties .

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
filtering tabs (most popular/a-z/categories)
issue: tab navigation skips & for A-Z tab, screenreader says "AH ZED"
solve: add aria-label (description) and make tab works for switching search types
> filtering tabs (most popular/a-z/categories)

- angularjs-portal-frame/src/main/webapp/css/angular.less
- angularjs-portal-frame/src/main/webapp/frame.jsp
- angularjs-portal-frame/src/main/webapp/js/app-config.js
- angularjs-portal-frame/src/main/webapp/portal/main/controllers.js
- angularjs-portal-frame/src/main/webapp/portal/main/partials/header.html
- angularjs-portal-home/src/main/webapp/js/app-config.js
+ Removes `beta-header` from the frame
+ Externalized the sub title (beta) so people can choose what they want
I just removed the directive and less import, but didn't delete the source. Just in case we wanted to utilize these things in the future.
> MUMUP-1948 : Remove beta header, will fully delete at a later date

- angularjs-portal-frame/src/main/webapp/css/buckyless/notifications.less
We had this hover move thing going on as part of the demo. Just cleaning it up a bit so just the background color shade changes a bit.
> Fix hover state of notification on full

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-view.html
- angularjs-portal-home/src/main/webapp/my-app/layout/route.js
- angularjs-portal-home/src/main/webapp/my-app/main.js
Instead of hitting `/list` as the default then redirecting to `/widget` if you are in that view, this hits a loading page which then directs you to either list or widget.
> MUMUP-1879 : Add in default page that decides if you goto list or widget or x

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
could recognize all containers title on widget page now.
also skip the icon for not repeat read the {{::portlet.title}} again.
> improve the accessibility for widget view

- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
Note that the initial landing on the page won't trigger an event
> MUMUP-2032 : add google events for categories

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
Portlets' title able to get by TAB
the user will know which portlet it is before they "launch" it
make all of those four columns able to be read out in vertical order ( title -> content under the title)
> Accessibility improvement - apps/details/  page

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-mock-portal/src/main/webapp/WEB-INF/web.xml
- angularjs-portal-mock-portal/src/main/webapp/general-error.html
- angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
+ MUMMNG-1812 : Cleanup controller filter for widgets. There was a weird state of the filter (going to be used for time & absence portlet) where the service hasn't returned yet but we were trying to run the filter on an undefined object. It would vomit errors in the log. This checks for null first now. :)
+ MUMUP-2090 : Add generic error page in mock data with a redirect link to `/web`
+ EC : Add directory widget to `layoutDoc`
> Misc Cleanup

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
- angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
I think I broke the old pull request for this, so I created another one.
Continuation from https://github.com/UW-Madison-DoIT/angularjs-portal/pull/316
Added a dropdown button that, when clicked, gives the user the choice for weather in imperial units or metric units. 
The code I added is in the weather widget controller (between lines 46-106 of controllers.js). The functions on lines 77 and 90 are called when the user clicks an item on the dropdown menu, and that does the calculations from Fahrenheit to Celsius, and from Celsius to Fahrenheit.
Temperature in degrees Fahrenheit
Dropdown button is clicked.
Temperature is now in degrees Celsius
The reason the images are not showing is because I was running this locally on the angular-mock portal, and I think that's also why the temperature …
> MUMMNG-1524: Adds metric units to weather widget - UPDATED

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/weather.html
Fahrenheit (F) button no longer stays gray when it's not clicked, and the buttons no longer overlap or get buggy when the widget width changes.
> Fix final bugs for the weather widget units change

- angularjs-portal-home/src/main/webapp/css/uw-portlet.less
Good catch @keirserrie. Removed font style so the Help page takes Helvetica, not FontAwesome.
> MUMMNG-1667: Fix font on Help page from Font Awesome to Helvetica

- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/js/master-app-config.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
- angularjs-portal-mock-portal/src/main/webapp/web/marketplace/entries.json
When the user searches and finds zero search results, 
* Clearly state that no results matched
* Suggest ways to recover
Suggestions implemented in this changeset:
* dropping the category filter, iff matching results are hidden by the category filter, 
* showing non-launchable matches,  iff matching results are hidden by the "Show all" filter
* searching in the directory, with a link that carries along the active query string
* searching in UW Madison web search, with a link that carries along the active query string
* searching in the KB, with a link that carries along the query string
* asking the Helpdesk for help
* submitting feedback about MyUW search
The external search URLs are configured in `app-config.js`, in that
* Directory search URL is configurable; if not set this option is …
> MUMUP-2155 : Friendly zero search results

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Only show the no-search-results recovery content after the array of portlets available for filtering is non-empty.
While loading:
After loading:
Tested locally using Chrome dev tools throttling, which is pretty cool.
> Only show no-results content after portlet registry loads.

- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/js/master-app-config.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Adds "Search for events instead" as another no-search-results recovery option.
This tweak is intended to be responsive to a request around content in MyUW supporting the [AAU Survey Student Engagement Sessions](https://today.wisc.edu/events/search?utf8=%E2%9C%93&term=AAU+Survey+Student+Engagement+Session&commit=Search) without committing MyUW to adding a `portlet-definition`, widget, entry in the directory of apps, notification, etc., supporting these three point-in-time events.
The specific zero-search-results search that raised the concern was a search for "sexual assault" and concern that this yields no search results. The compromise initial response is "we're not able to immediately make that search term directly yield useful content, but if people were searching for this event, …
> MUMUP-2163 Add events search as a recover option

- angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json
Tweak the text of the notification about missing/broken SSN to clarify that it's talking about the Personal Information module in Student Center rather than the app named "Personal Information" in MyUW.
> MUMMNG-2055 tweak missing SSN notification prose.

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Read about `ng-switch` and thought this would be a good case to use it. Did a little logging, for someone that has a single widget on there page, it reduces the amount of calls to `widgetCtrl.portletType(portlet)` from 188 to 42. Decent improvement.
> use ng-switch for widget selection

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/search-with-links.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- angularjs-portal-mock-portal/src/main/webapp/web/layoutDoc
+ Creates SWL directive for a search with links widget template
+ If you set widgetType = 'search-with-links'
+ and provide proper config
```json
{
"actionURL":"https://www.bing.com",
"actionTarget":"_blank",
"actionParameter":"q",
"launchText":"Launch Bing",
"links":[
{
"title":"Interweb Search",
"href":"http://www.bing.com",
"icon":"fa-search",
"target":"_blank"
},
{
"title":"Image Search",
"href":"https://www.bing.com/images",
"icon":"fa-camera",
"target":"_blank"
}
]
}
```
note: links is limited to 2, but does handle if there are 1 or non.
> MUMUP-2245 : Search with links Template

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html
Three things were done:
1. Remove bootstrap padding on columns in list-of-links widgets
2. Define height of 95px
3. Truncate after 24 characters (code change in uw-frame)
Before:
After:
> Make list-of-links widget type more responsive

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
The no-search-results recovery link about asking for help didn't match the Help Desk's [branding as Help Desk](https://kb.wisc.edu/helpdesk/). This fixes that.
> Brand Help Desk correctly (rather than Helpdesk).

- angularjs-portal-home/src/main/webapp/css/my-app.less
- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/search-results.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/routes.js
Search results a la @keirserrie mockups. Clean, simple, googley.
Holding off on Directory and Wisc.edu tabs until we have those in place. With this PR, new search results page is shippable. 
Also note this is a new and separate page from the Browse page. The Browse page will stand as is until we decide what to do with it.
Search: 'email'
Search: 'time'
Search: 'sched'
Search in action (it's blazingly fast :fire:):
> MUMUP-2196: Redesign search results

- angularjs-portal-home/pom.xml
- angularjs-portal-home/src/main/webapp/css/home.less
- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
- angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html
- angularjs-portal-home/src/main/webapp/my-app/layout/static/partials/static-content-max.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
- angularjs-portal-mock-portal/src/main/webapp/web/session.json
https://github.com/UW-Madison-DoIT/uw-frame/pull/111 is required for this change. Please review that first.
This utilizes the new changes from `uw-frame`.
Changed the following pages to use the new app-header directive:
+ marketplace header 
+ home header
+ search results
+ static
+ exclusive
+ Note that the add to home action link doesn't work for the static page due to the way that was implemented. I added it to the options menu for now, we can make that better later.
> MUMUP-2288 : Bye sidebar

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/routes.js
- angularjs-portal-mock-portal/src/main/webapp/Login
Depends on https://github.com/UW-Madison-DoIT/uw-frame/pull/134 being merged.
+ Removes all `miscService.pushPageview` hits (this happens anytime the route changes now)
+ Configures the search result page to be successful for GA Site Search
+ Unrelated changes: white space (I blame atom), added a `/portal/Login` success page in mock so you don't get redirected to `/portal/Login` every time you hit `/web`
> MUMUP-2139 : angulartics impl for angularjs-portal

- angularjs-portal-home/src/main/resources/endpoint.properties.example
- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/services.js
So I changed the order of the display items a little bit from the [mockups](https://docs.google.com/presentation/d/18OzygRCY4npTOu_tnBgUogLitto0kjWMRRz1t7Cn8dQ/edit#slide=id.g74158e4a7_0_30) and I added in a see more link.  Both things that we can change @keirserrie 
Also fixed the bug where zero wisc domain results had empty number
> Wisc directory results

- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Filters work on the search results page. I used jQuery to do this, because it seemed like the easiest option.
Room for improvement: 
- Loading state. Initial load takes 5-7 seconds to get results, but doesn't show the user that more results are coming. 
- We might want to show a 'No results' paragraph for each section, so that when you filter it to, say, MyUW results and there are none, it isn't blank.
We can try to get these improvements in before releasing tomorrow, but I think we should at least get this in.
> Filter search results

- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
ONE. Takes Andrew's commit of Not showing "No Directory Results" when there are too many.
TWO. Removes the see all directory results link when focused on directory tab.  Also the see all results directory link works and goes to the tab
THREE. We now show all the search results (removes the limit) when focused on tab to align with mockups and link text
> Directory enhancements

- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Took @apetro's good thought from https://github.com/UW-Madison-DoIT/angularjs-portal/pull/391 on removing the tab subheaders and combined it with @timlevett's good thought of untilizing the solution already in place.
> Removes the header from specific tabs on search results

- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Removes the see all # directory results if the number of results shown is equal or less than the limit.
So, you don't see the 'see all link' for [0,3]
> Removes see all directory is already showing all

- angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json
Implements the new MyUW version of the old MyUW welcome tab content prompting graduating seniors to provide their plans beyond UW-Madison.
Text from Sara Lazenby.
Mockup:
> MUMMNG-2361 Notify graduating seniors of unfulfilled post-grad plans survey opportunity

- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
#consistency
I also removed the "Showing # of # results" section. Don't think anyone will miss that but let me know if that's too big of a change to introduce.
> Tabs in marketplace

- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
+ If one searches for something, then reads about details, then clicks back, it goes back to there search result 
+ If one browses for something, then reads about details, then clicks back, it goes back to there browse session
+ Changed from custom style for categories to use the outline button with some different coloring. 
+ Changed details link to be an outline button
+ Changed that bottom area to be a grid
+ Now if you hit a search result from where ever it'll have the search term in the search box (this was done in https://github.com/UW-Madison-DoIT/uw-frame/pull/157 and https://github.com/UW-Madison-DoIT/uw-frame/pull/158)
> MUMUP-2366 : Details page back to x

- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html
+ Changed wording (based on feedback) to "Login".
+ Turns out that uPortal makes it so guest cannot add anything, so we only have the option of saying "you can launch the things that are on your home screen". I'd rather not play around with the render code :)
+ Also fixed margin so it aligned with the details button of the same styles
_Note using mock data for after screenshot, so don't get too caught up with which ones you can launch vs. login_
> MUMUP-2395 : Change wording on launch/login for guest

- angularjs-portal-home/src/main/resources/endpoint.properties.example
- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/services.js
Only shows google search if the user is in a configured group.  Otherwise no search result section shows. 
Example for River Falls user with no google search configured:
Example for River Falls user with google search configured:
There is some work to do so that the `No Matches` suggestions are configurable.
> Configurable google search results

- angularjs-portal-home/src/main/webapp/js/app-config.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
- angularjs-portal-home/src/main/webapp/my-app/search/services.js
Now when you get zero search results and you are not in the UW-Madison group, you'll only see the help that's configured.
Example of UWRF on search:
Example of UWRF on browse:
But of course, at UW we have the whole collection configured:
and
> Zero search result state

- angularjs-portal-home/src/main/webapp/js/app-config.js
( [MUMUP-2439](https://jira.doit.wisc.edu/jira/browse/MUMUP-2439) , tweak on changes in #419 .)
Per [KB documentation](https://kb.wisc.edu/page.php?id=15303), the DoIT Help Desk is the right contact for non-username-or-password-related issues for `my.wisconsin.edu` portal users, including UW River Falls.
By the time one sees the UW-River-Falls-specific search config, one is logged in, so the not-username-or-password-related hurdle is already jumped.
So configure the same `helpdeskURL` for UWRF as is configured for Madison.
> MUMUP-2439 Configure DoIT Help Desk URL as helpdeskURL for UW River Falls.

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
This console.log statement clutters up the console, and started to bother me. Anyone need this in there?
> Remove console.log statement

- docs/Dockerfile
- docs/build-docs.sh
- docs/markdown/compact.md
- docs/markdown/expanded.md
- docs/markdown/home.md
- docs/override.js
Add in template for building out the documentation for angularjs-portal.  This uses https://github.com/UW-Madison-DoIT/uw-docs to generate a Docker container containing the markdown from this repo.  We will then post the Docker container on tools.my.wisc.edu/docs/angularjs-portal (or something like that).
> angularjs-portal docs section

- angularjs-portal-home/src/main/webapp/js/override.js
Adjust "/web portlet rendering" beta setting description to reflect that 
* it's just expanded widgets that do not reflect `webPortletRender`, 
* rather than just compact widgets that do reflect it.
> Clarify that webPortletRender affects e.g. search results launch links.

- docs/markdown/search.md
I got to thinking about the need to document, understand options for adopting campuses that came up at sprint review yesterday.
Idea: documentation about `angularjs-portal` search features, in the `docs` directory.
> Stab at search.md for documenting search.

- angularjs-portal-home/src/main/webapp/js/override.js
No longer overrides the back2classicURL and removes the footer url inviting users to go back to MtyUW old
> MUMUP-2478 turn of old my.wisc

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html
Adds the target attribute to be config.target, and then I will set the target to be equal to "_blank" in the outages entity files so that not all rss widgets are affected.
> MUMUP-2346 : See all link in outages rss widgets should open new tab

- angularjs-portal-home/src/main/webapp/staticFeeds/notifications.json
- angularjs-portal-home/src/main/webapp/staticFeeds/old_notifications.json
* Burn prematurely notified (and possibly prematurely dismissed-by-individual-employees) id 7.
* Re-post the notification with id 9.
Net effect will be for employees to be notified anew regardless of previous notification.
> MUMMNG- 2401 Re-notify wrt 2015 WRS Statements of Benefits availability.

- angularjs-portal-home/src/main/resources/endpoint.properties.example
- angularjs-portal-home/src/main/webapp/js/web-config.js
Alternative to https://github.com/UW-Madison-DoIT/angularjs-portal/pull/465
Updates wisc.edu search to up-to-date api.  Differs in https://github.com/UW-Madison-DoIT/angularjs-portal/pull/465 by not using the callback param, so no need to parse out comment.
After:
> MUMUP-2548 Fixes wisc.edu google search

- docs/markdown/expanded.md
In the documentation about the `list-of-links` widget type, note that `launchText` is now optional per #469. .
> Document lol widget launchText optionality

- angularjs-portal-home/src/main/webapp/WEB-INF/web.xml
- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/single-widget-component.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/routes.js
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- angularjs-portal-mock-portal/src/main/webapp/web/portlet/wisc-mail.json
+ Refactored a lot of the widget functions into a base controller
+ Adds `<widget fname="fname"></widget>` component. fname is one way bound using the new component. This then calls for the meta data of that widget, and then processes the portlet.
+ Adds a full screen widget view at `/web/widget/:fname`. Currently nothing links to that.
+ Adds a widget preview section to the details page.
> MUMUP-2579 : Widget component

- angularjs-portal-home/src/main/webapp/css/home.less
- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
+ Add in `md-card` for widgets and compact mode.
+ Moved css for widgets to `widgets.less`
+ sorry for the white space change, here is a w=1 link https://github.com/UW-Madison-DoIT/angularjs-portal/pull/478/files?w=1
We may want to adjust the header padding. Looking at the shots, we are giving a bit more in the new, which could mess up some widgets.
> Switch the widgets to md-card objects

- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/css/variables.less
- angularjs-portal-home/src/main/webapp/js/override.js
- angularjs-portal-home/src/main/webapp/js/web-config.js
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- package.json
In this PR:
- Added angular material elements
- Layout uses angular material instead of boostrap
- Added a "start" and "prestart" script to the node package so we can run the app with just `npm start` (saves a couple keystrokes)
- Removed a bunch of "px" from "0px" in CSS
- Replaced hard-coded colors in `marketplace.less` with references to colors in `variables.less`
**To do**
- Remove unused CSS
- Adjust other marketplace views so they conform to the updates (ex. replace the "add to home" and "launch" buttons in the search results view with toned-down material versions)
> Update details view per recommendations from Keir

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
In this PR:
- List-of-links widgets will display as default widgets if the following criteria are met:
- `widgetType` is list-of-links
- there is only one link in `widgetConfig.links`
- `altMaxUrl` is true
- the URL of that link is the same as the portlet's `url` attribute
**Note:** I tested this by changing the mock data so that the Manager Time and Approval widget meets all the criteria mentioned above. I did not push those changes.
> List-of-links with single link should fall back to normal display

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Widget body is now 100% height with a 36px bottom margin (the height of the "launch" button). This should ensure that all of the widget's content is displayed, but it's not a perfect fix. I think the underlying structure of widgets should be revisited long-term. I also plan on materializing the `<circle-button>` directive, which should help.
> Hotfix materialized widget display issues

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
In this PR:
- Portlet title padding increased (so that content is not smashed up against title text)
- Structure/style of some widget types adjusted so that content is center-aligned vertically and horizontally
- mode toggle menu rewritten in material so that it fits in new, material frame
**Note**: You'll also notice that the circle buttons don't look quite right. There are some changes included in my uw-frame material PR to improve their appearance.
> Adjust size/positioning of elements for some widget types

- angularjs-portal-home/src/main/webapp/js/override.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
Annette asked me to grab the ratings details for a particular app.
In the interest of enabling fishing:
Adds a beta setting:
If (default) not set, details page presents ratings as before.
If the beta setting is set, the details page presentation of ratings is enhanced with a hyperlink
to the raw JSON API.
```JSON
{"ratings":
[
{"rating":5,
"review":"Exactly what you need to know about your Wiscard and the most important direct links for managing it - which aren't easy to find otherwise."}
]
}
```
Note that authorization is applied on the JSON API itself, so while anyone could flip the beta setting to get the hyperlink, this has no security implications.
The raw JSON API is probably a "good enough" administrative user experience for accessing this data for now, though of course it will be …
> MUMUP-1536 link ratings API from details page, if beta setting.

- angularjs-portal-home/src/main/webapp/css/home.less
Changes to widget styles caused the "add to home" widget to display incorrectly. This is a fix for that specific widget.
> Fix display of add-favorites widget

- angularjs-portal-home/src/main/webapp/js/master-override.js
Change defaultTheme to use first theme instead of group API service, which does not exist in base uPortal. Also changed to default uPortal tab.
> Set default theme to first one and tab to 'Welcome' in master-overrides.js 

- angularjs-portal-home/src/main/webapp/css/home.less
- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
In this PR:
- Toast message no longer appears upon removing a widget from home
- Hovering a compact widget no longer changes the widget's text/icon colors
- Fixed a bug where hovering some widgets did not change the cursor to a pointer (now all widgets behave the same on hover)
- Added a CSS transition to the add-favorites widget so it's background color changes smoothly instead of instantly
> Remove removed-widget toast and widget hover color

- angularjs-portal-home/src/main/webapp/css/widget.less
Noticed that IE still had the clipping issue, where some of the widget content was not visible. Made a small change that should fix it for now. I still think the overall structure of widgets should be overhauled in the future.
> Improve cross-browser consistency of widget appearance

- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
Noticed during sprint review that "expand widgets" toggle was using a darker hue of the accent color, which is hard to see for some themes. This PR changes it back to using the default hue of the accent color.
> Fix toggle using alternate hue of accent color

- angularjs-portal-home/src/main/webapp/css/marketplace.less
Launch button is no longer in all caps:
> Remove uppercase text-transform from marketplace details widgets

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/lol.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/option-link.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/rssfeed.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/search-with-links.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Widget consistency (or lack thereof) has been on my mind for a long time now. I want to get this up for the sake of gathering info/feedback before I spend too much time on this. It can always be tabled for later.
- Removed percentage-based sizes from most widget-related container classes (and replaced those with hard-coded pixels, since we know widgets will always be 290px high)
- Replaced/removed some bootstrap classes:
- `option-link` widget input is now material
- `list-of-links` widget now spaces its circle-button links with flex grid instead
- launch buttons are no longer bootstrap buttons
- `simple` and `normal` widget icon position is now flex-based
**Notes:** 
- This PR is part of a package that includes [myuw-overlays/entities …
> Improve consistency of widget appearance

- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
Due to a race condition during the run block in `/portal/main.js` we cannot assume that `$sessionStorage.portal.theme` will exist. $sessionStorage.portal will exist however because of the preloading we are doing in `/main.js` for angularjs-portal.
> MUMUP-2719 If the theme isn't selected, one cannot grab the rgb from it

- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
This PR satisfies the requirements of [MUMMNG-2694](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2694)
- Replaced old tab navigation with angular material tabs and custom badges
- Added some material buttons to MyUW search results
**Notes:**
- This PR depends on [uw-frame PR#318](https://github.com/UW-Madison-DoIT/uw-frame/pull/318) in order for the tabs to appear as pictured
- I plan on backlogging a new story to explore more design options for search results
- It might be worthwhile to create a generic `search-results` directive that we can reuse for each category of results. The current version functions fine as is, but a directive would help cut down on copy+pasted code.
> Materialize search results page

- angularjs-portal-home/src/main/webapp/css/search-results.less
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-load-more.html
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/directives.js
- angularjs-portal-home/src/main/webapp/my-app/search/partials/campus-domain-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/partials/directory-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/partials/marketplace-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
- New directive for each type of search results (only serves to reduce copy+pasted code)
- Fixed a bug that made the "load more" button for MyUW results never appear 
- Currently in prod, if you search a term that would return more than 20 results (like the letter "r"), you will only get 20 results and the "load more" button will not appear
- Made the marketplace "load more" button sentence case
- Minor style tweaks
- Got rid of some unused jQuery in the search controller
> Create directives for types of search results

- angularjs-portal-home/src/main/webapp/css/widget.less
> fix issue where simple widgets launch was not centered in ff

- docs/markdown/widget-launch-button.md
- docs/markdown/widgets.md
- Broke up chunks of the doc with headings
- Simplified much of the text
- Added some other formatting to draw attention to the most important parts
- Moved text that applied to widgets into the widget documentation
- Removed suggestion to use `aria-labelledby` in favor of `aria-label`
- Added suggestion to use `<launch-button>` directive
> Make launch-button guidance more readable

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- structural html change to fix display of simple/normal widgets across browsers
- added an aria-label to widgets that allows screen readers to read "[app title] widget" instead of "unknown"
**Notes:**
- I was unable to test in IE because my VM is having issues. IE 10 and later support the Firefox draft of flex, so the `-webkit` prefixes should be sufficient. Older versions may require additional prefixing. This should be tested.
- Adding [postcss/autoprefixer](https://github.com/postcss/autoprefixer) to our build process will provide the following benefits: 
- Browser inconsistencies will become irrelevant and we should see fewer (if any) issues like this
- Our .less code will be easier to read and maintain (we won't have to have a ton of extra lines of code for vendor …
> Fix widget rendering problems

- angularjs-portal-home/src/main/webapp/css/marketplace.less
- angularjs-portal-home/src/main/webapp/css/variables.less
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
- Removed bootstrap buttons for MyUW app categories and replaced them with material chips
- Removed some unnecessary CSS
- Added aria-labels to category chips
> Replace categories buttons with material chips

- angularjs-portal-home/pom.xml
Because uw-frame 2.8.0 released, so 2.8.1-snap is the now active snap.
> Build on uw-frame 2.8.1-snapshot rather than 2.7.1-snapshot.

- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- package.json
This PR goes hand in hand with [uw-frame pull #331](https://github.com/UW-Madison-DoIT/uw-frame/pull/331)
- Removed bootstrap tooltips from the "widget info" button, replaced with material tooltip
- Removed some CSS that should be in frame
- Added `mvn clean` to the npm start script
> Replace widget action popovers with material tooltips

- angularjs-portal-home/src/main/webapp/main.js
So there is a bug where `$sessionStorage` in `/main.js` doesn't persist to the actual session storage, super weird. This patch fixes that by doing what the underlying library does.
This fixes 2 things:
+ Impersonate now works
+ Everytime someone hits /web they are not reauthenticated by hitting `/portal/Login?silent=true`
> Patch always logging in issue

- angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
Recent changes to the "widget info" tooltip didn't include compact widgets, and they broke. This PR fixes them.
> Fix display of compact widgets

- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
Bug - without web search or directory search enabled, the whole md-tabs would be hidden.
Cosmetic fix - no search results section was not consistent with other search result padding
Shows the MyUW only tab when there is another tab to show (web or directory).
Needs ng-if vs ng-show, because the tab markup still exists with ng-show resulting basically empty tabs.
Before without a web search or directory search enabled:
Before with the no-results styling and results enabled:
After without a web search or directory search enabled:
After with only 1 enabled:
> MUMUP-2766 Allows MyUW search results if no extra search specified

- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- "NORMAL" widgets now use the `<launch-button>` directive and have an `href` attribute
- "SIMPLE" widgets still use plain `<button>`, but they now have an `ng-click` attribute
> Fix broken launch buttons

- .gitignore
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
[MUMUP-2807](https://jira.doit.wisc.edu/jira/browse/MUMUP-2807)
- Added aria-labels to elements that were being skipped by screen reader
- Changed the "info" button's role to a tooltip and provide the tooltip text as the button's aria-label
Overall this results in a smoother experience when using a screen reader, with clearer context when navigating by keyboard.
> Improve portal home accessibility

- angularjs-portal-home/src/main/webapp/my-app/layout/services.js
- docs/markdown/widgets.md
Okay, here's the deal.
We're pivoting from 
Status quo:
the RSS widgets declaring an RSS URL and that RSS URL needing to be fed to an out-in-the-cloud converter, 
to 
RSS widgets declaring a URL that produces the needed JSON directly (that happens to be an RSS to JSON conversion service, taking as a parameter a key indicating what RSS feed ought to be converted).
(For an example of this pivoting, see [this test tier entity change](https://git.doit.wisc.edu/myuw-overlay/entities/merge_requests/464/diffs).)
It might be better to support configuring the RSS widget in any of the three ways, that is
1. With the URL of the actual desired RSS feed. This is in some sense simplest. The RSS widget Type would then have the responsibility of applying however it is that one retrieves and converts RSS …
> Hack: RSS widget config now is JSON URL rather than RSS URL.

- README.md
Continuing experimentation with automating some aspects of code review:
codeclimate.com is analyzing this repo gratis because it's open source.
This changeset simply adds the shiny badges to the README, documenting and linking the available codeclimate.com reporting.
Could go further and invite codeclimate.com to analyze, comment on pull requests. Looking at the report, seems like there are a lot of issues it would nag about, so maybe we'd want to address a bunch of those issues in the course of turning that on to manage the noise. Maybe try out the badge and see if anyone finds its reporting useful first?
> Add codeclimate.com badges

- .gitignore
- docs/Gemfile
- docs/_config.yml
Makes the new GitHub Pages Jekyll-driven angularjs-portal docs less ugly
simply by adopting the `dinky` theme.
In doing so adds enough configuration to allow running Jekyll locally
```
bundle exec jekyll serve
```
to enable local testing. Here's what it looks like locally for me:
UPDATE: and here it is [previewed for reals on GitHub Pages](http://apetro.github.io/angularjs-portal/).
> MUMUP-2825 angularjs-portal docs: now less ugly

- .editorconfig
- angularjs-portal-home/src/main/webapp/css/widget.less
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-card.html
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/partials/widget-creator.html
- docs/widgets.md
- Added CSS styles for maintenance mode "overlay" (meaning: A thing that goes on top of widgets)
- Added HTML markup for maintenance mode
- Added maintenanceMode attribute to widget creator templates
- Added info about maintenance mode to the widget documentation 
- Added working widget docs link to widget creator page
- Add `.editorconfig` to ensure consistent code style (same as uw-frame)
*Notes: I'm confident it'll work, having tested it with the widget creator, but it should still be tested with a real widgetConfig for a real widget. Also, please ignore the whitespace gore in widgetController. I was desperate to add some missing semi-colons and this project has no code style configuration :/*
> Add maintenance mode styles and markup for widgets

- angularjs-portal-home/src/main/webapp/my-app/layout/partials/home-header.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-no-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/partials/marketplace-results.html
- angularjs-portal-home/src/main/webapp/my-app/search/partials/search-results.html
- docs/README.md
- docs/_includes/footer-aside.html
- docs/app-directory.md
- docs/assets/css/style.scss
- docs/search.md
- docs/widgets.md
- Replaced hard-coded references to MyUW with `{{portal.theme.title}}`
- Adjusted docs to reflect changes
- Adjusted docs to make sure all references to angularjs-portal are formatted the same
- Adjusted docs styling to match uw-frame (sidebar list)
> Remove hard-coded 'badgerisms' from user-facing content

- .travis.yml
Travis CI runs tests on different JDKs in parallel.
So there will be the benefit of additional plaform testing, without much
of a performance hit.
Build output https://travis-ci.org/ChristianMurphy/angularjs-portal/builds/211589663
> Test against multiple JDKs

- package.json
also updates author field to attribute University of Wisconsin.
> Update license in package.json to Apache 2.0

- README.md
No active `angularjs-portal` maintainers are maintaining the Codenvy assets. The badge is broken; the instructions probably don't work. Remove the noise.
> rm codenvy from README

- package.json
'posttest' automatically runs after 'npm test'
> Issue #582: Add ESLint to package.json test script

- README.md
Spacing between [] and () prevents [commonmark based parsers](http://spec.commonmark.org/0.27/#links), like [GitHub flavored markdown](https://github.github.com/gfm/#links), from being able to identify text as a link. 
This removes the space to ensure it will be parsed correctly.
Also normalize line endings to LF.
----
> Remove space between [] and () in links

- angularjs-portal-home/src/main/webapp/js/login-config.js
- angularjs-portal-home/src/main/webapp/js/master-override.js
- angularjs-portal-home/src/main/webapp/js/override.js
- angularjs-portal-home/src/main/webapp/js/web-config.js
- angularjs-portal-home/src/main/webapp/main.js
- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/services.js
- angularjs-portal-home/src/main/webapp/my-app/layout/spec/layout_controller_spec.js
- angularjs-portal-home/src/main/webapp/my-app/layout/spec/toggle_controller_spec.js
- angularjs-portal-home/src/main/webapp/my-app/layout/static/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/static/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/static/routes.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/widget/routes.js
- angularjs-portal-home/src/main/webapp/my-app/main.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/marketplace/services.js
- angularjs-portal-home/src/main/webapp/my-app/rating/components.js
- angularjs-portal-home/src/main/webapp/my-app/rating/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/search/services.js
- package.json
Broad but hopefully thin changeset for fixing the Lint errors we should fix, and being warned about the ones that we can fix as we go.  The goal is to stay as close to Google's eslint standards as we can. Rule Overrides will be documented as line comments in the pull request.
----
> Fix Lint Errors for TravisCI

- package.json
Automatically ban ES6+ syntax from the application (needed for continuing IE support)
----
> Error linter when ES6+ syntax is used

- angularjs-portal-home/src/main/webapp/my-app/layout/directives.js
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/default-card.html
I accidentally deleted the greatly named default-card.  Turns out that they're actually used for compact mode.  Added a comment.
----
> MUMUP-2898 Adds compact mode back in

- .travis.yml
One of the main remaining slow downs on Travis is download time of maven and npm dependencies.
This PR sets up [Travis CI caching](https://docs.travis-ci.com/user/caching/), which stores necessary files in an S3 bucket that is mounted at the start of each build.
Reducing time spent fetching files from maven central and the npm registry.
:notebook: initial PR will show a slower build time as the S3 cache is generated, future PRs and commits will show the speed up.
----
> Cache dependencies to reduce download time on CI

- committers.md
So that Committers can then bootstrap future Committers.
----
> Formally bootstrap Committers

- docs/README.md
- docs/contributors.md
Add docs page gratefully acknowledging the contributors.
Initial draft had more detail, but after reflecting on [the page on credit in Producing Open Source Software](http://producingoss.com/en/credit.html), pivoted to minimalist.
----
> Acknowledge contributors

- README.md
- docs/README.md
- docs/apereo-incubation.md
- docs/releasing.md
**This is nuanced and is going to need Committer follow-up on `uportal-dev@` after merge.**
+ Adds releasing page, noting that we've adopted Apache rules and linking them for releases.
+ Raises awareness of in-progress project name change.
+ Tweaks Apereo Incubation badge to [the new preferred badge implementation](https://groups.google.com/a/apereo.org/d/msg/incubation/p2h2ypnATO0/vsv9zzx9EQAJ).
*Not* my intention: add a lot of painful friction to releasing.
My intention: more open source project "legitimacy" through following the process and policies we are trying to adopt.
So, specifically, what I think needs to happen is:
+ In general, more talking about `uPortal-home` release engineering on `uportal-dev@`.
+ In specific, a vote of the Committers authorizing at least @vertein and …
> Clarify releasing under Apache rules

- angularjs-portal-home/src/main/webapp/my-app/layout/services.js
Bit of progress peeled out from #633 .
Detects when the configured layout web service is uPortal DLM layout.json v4-3.
This implementation is ugly. It could maybe benefit specifically from a refactor to use `map` effectively, and definitely more generally from attention from someone more comfortable with idiomatic JavaScript.
More importantly: could benefit from refactoring to make the canonical representation of layout simply a flat array of String fnames, since that's all modern `uPortal-home` needs. That'd be huge.
Finally, no attempt at unit test coverage for this change. :/
----
> Detect and support layout.json v4-3

- README.md
- angularjs-portal-home/src/main/webapp/js/README.md
- angularjs-portal-home/src/main/webapp/js/master-override.js
- angularjs-portal-home/src/main/webapp/js/override.js
- angularjs-portal-home/src/main/webapp/my-app/layout/services.js
- docs/README.md
- docs/with-uportal.md
Documenting how to adopt with real live bleeding-edge `master` uPortal-that-will-be-5.0.0.
Documents
+ Configuring `uPortal-home` for integration with localhost `uPortal`.
+ Getting Tomcat, uPortal, and uPortal-home running together
TODOs for:
+ Digging into the integration, including how the portlet registry functions as the app directory backend, the portlet definitions contain the metadata driving widgets, how `uPortal-home` delegates to `uPortal` for some Portlet rendering, and how `uPortal` can delegate to `uPortal-home` for the home page experience.
----
> Document implementing with vanilla uPortal master

- .travis.yml
Resolve CI failure in #638 by adding Chrome 59+ to CI environment.
Adds macOS testing.
----
> Add Chrome to CI, test with macOS and Ubuntu Trusty

- committers.md
Add Christian Murphy as Committer, per [unanimous vote of existing Committers](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/qcl7cyVWCDU/Z_mUyIXBAQAJ).
----
> Add committer Christian Murphy

- angularjs-portal-home/src/main/webapp/js/override.js
layout.json is full of weird quirks, one of which makes testing locally not work at all. Reverting to layoutDoc for local builds.
----
> reverting to layoutdoc

- .travis.yml
1. Detect whether the current CI build is caused by Greenkeeper
2. Update the lockfile with the latest version of the updated dependency using the package manager’s built in mechanism
3. Push a commit with the updated lockfile back to the Greenkeeper branch
reference: https://github.com/greenkeeperio/greenkeeper-lockfile#how-does-it-work
----
> fix(ci): Update Travis CI script so greenkeeper works with the lockfile

- angularjs-portal-home/src/main/webapp/my-app/layout/partials/remove-button.html
[MUMMNG-3581](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3581): "Let user rm widgets in maintenance lifecycle state"
- Stop hiding the remove widget button in maintenance mode
----
> Make widgets removable in maintenance mode

- docs/presentations.md
Use single space, alas not newline, in defining reference link.
Most pedantic pull request ever.
----
> fix broken GitHub Pages build by rm whitespace

- package-lock.json
- package.json
Also updates `remark-preset-lint-recommended` which updated after the `greenkeeper/initial` branch was created but before it was merged.
Causing greenkeeper to miss it.
:warning: **NOTICE** :warning: 
When testing and after merge please run `rm -rf node_modules & npm install` to ensure dependencies are at latest version.
----
> fix(package): Lock requirejs-text to npm released version

- CHANGELOG.md
Based off the excellent feedback from #666 :smiling_imp: 
:information_source: About Keep a Changelog
This takes a different approach to keeping a changelog.
Rather than a primarily automated process based off commit messages. :robot: 
This takes the purely human approach of letting the release manager add a description of changes. :memo: 
While still offering some recommendations on how to structure the changelog.
:link: from [Keep a Changelog docs](http://keepachangelog.com/en/1.0.0/)
*  Changelogs are *for humans*, not machines.
* There should be an entry for every single version.
* The same types of changes should be grouped.
*  Versions and sections should be linkable.
*  The latest version comes first.
* The release date of each versions is displayed.
* Mention whether you follow …
> docs(changelog): Add release notes 6.0.0 to present to changelog file

- angularjs-portal-home/src/main/webapp/my-app/search/services.js
PortalGroupService was renamed to portalGroupService in the messages refactor. This updates search to use the new name.
----
> updating search to use the renamed portalGroupService

- dependencyci.yml
Configures DependencyCI to ignore flaky maven checks.
This allows DependencyCI status to be re-enabled and to provide meaningful results.
----
> ci: Configure Dependency CI

- README.md
split badges into three sections
1. current project status
2. standards used in project
3. incubation status
sectioning badges should help adopters identify different types of key information faster.
In addition adds more status and standards badges
* add maven central version badge.
* add npm dev dependency status badge.
* add bithound status badge.
* add SemVer 2.0 standard badge.
* add Keep a Changelog 1.0 standard badge.
* add Conventional Commits 1.0 standard badge.
* add Commitizen badge friendly badge.
* remove code climate issue count badge.
depends on #666 and #671 
----
> docs(readme): add additional status and standards badges

- CHANGELOG.md
missing colon was preventing the reference link for release 6.6.0 from linking.
removed unreleased change notes that are now reflected in 6.6.0 release notes.
----
> docs(changelog): correct link for 6.6.0 release

- LICENSE
Apereo does not currently have an ICLA on file for @jiayinjx , an [already-acknowledged Contributor](https://github.com/UW-Madison-DoIT/angularjs-portal/blob/master/docs/contributors.md). Where included her contributions were intentionally Contributed, so at the least they can be licensed directly via [Apache2 clause 5](https://www.apache.org/licenses/LICENSE-2.0.html#contributions) regardless of ICLA status.
That is, in effect, bundle @jiayinjx 's Contributions as an Apache2-licensed bundled dependency. [Apache documentation suggests we don't actually have to do anything at all](http://www.apache.org/dev/licensing-howto.html#alv2-dep) in `LICENSE` to do this.
A closer audit might reveal that none of Liu's Contributions remain in the current product. While valued, the original …
> fix(license): Acknowledge Jianyi Liu contributions via Apache 2 clause 5

- pom.xml
this avoids a conflict between the conventional commit message linter and the maven release plugin.
resolves #682
----
> build(maven): configure maven release plugin commit prefix

- LICENSE
- NOTICE
- README.md
- angularjs-portal-home/pom.xml
- docs/apereo-incubation.md
- pom.xml
+ Add the [Apache2 boilerplate `NOTICE` file][]
+ Acknowledge included-in-war dependencies in `LICENSE`
+ Remove un-needed `JSTL` dependency so we don't have to untangle under what license we'd be redistributing it.
+ Update incubation status documentation to reflect this and other licensing progress since last incubation status update.
Attempts to apply [Apache guidance about composing NOTICE file and acknowledging dependencies in LICENSE file][Apache licensing howto].
As it turns out, the `NOTICE` file can be simple boilerplate, because the included dependencies don't rise to [ack-in-NOTICE technicality][Apache re modifications to NOTICE].
However, we do have an ECL 1.0 dependency: the Java logging implementation. [Apache's got a manageable amount of angst about this and emphasizes that …
> add Apache2 NOTICE

- angularjs-portal-home/src/main/webapp/js/web-config.js
- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/services.js
- angularjs-portal-home/src/main/webapp/staticFeeds/messages.json
Adds functionality to support adding a widget to the homepage from a mascot announcement
----
- [X ] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].
> Add from feature button

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html
- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace.html
Categories are confusing. Stop bothering users with them.
**Removes navigation tab within app directory.**
**Removes categories chips from app directory entries as rendered en masse.**
**Removes categories section from app directory details page.**
Categories are unfit for purpose because they are tied up with permissions. Gotta have permission on the category to see the category qua category, but permission on the category inherits as permission on the portlets within the category. In practice this is confusing, yields to misconfigurations, accidental permission grants, a mess.
Maybe someday no-permission-complications "tags" could be re-introduced as a feature. Maybe we'll never need it.
But for near term it has become clear that we want to only grant permissions at the individual …
> Remove "categories" from app dir UI

- docs/assets/css/style.scss
- pom.xml
Our github pages were looking funky:
vs, what it should look like
SCSS files used in jekyll have to start with a front matter comment and can't start with a header license.  This excludes scss files in the docs directory from having the license header added automatically and fixes the existing comment to move beneath the front matter comment.
Similar to https://github.com/UW-Madison-DoIT/uw-frame/pull/527
----
> fix(license): remove scss auto-license in /docs

- angularjs-portal-home/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
Suppress the Related Apps section on the app directory entry details page in the case where there are no related apps.
(MyUW recently locally hacked the back end so that there are never any related apps. Greatly improving performance. Turns out computing related apps is *really* expensive and since it's only ever shown on these infrequently-viewed details pages, removing the feature has good current tradeoffs).
----
> fix(app_dir): Only show Related Apps div if there are related apps

- angularjs-portal-home/src/main/webapp/my-app/layout/controllers.js
- angularjs-portal-home/src/main/webapp/my-app/layout/partials/app-header-options.html
many thanks to @Doug-Reed for finding the bug and @thevoiceofzeke for helping fix it.
----
> fix: disabling options rendering on non-home paths

- web/src/main/webapp/my-app/layout/partials/app-header-options.html
- In mobile app options, replace widget toggle with regular menu item
- Change "add more to home" => "add more" on small screens to avoid clipping
----
> fix(ui): Fix clipping app options on small screens

- .github/CONTRIBUTING.md
- CHANGELOG.md
- NOTICE
- README.md
- build.sh
- docs/README.md
- docs/_includes/footer-aside.html
- docs/apereo-incubation.md
- docs/app-directory.md
- docs/search.md
- mock-portal/pom.xml
- package.json
- pom.xml
- src/main/webapp/index.html
- web/pom.xml
- web/src/main/webapp/WEB-INF/web.xml
- web/src/main/webapp/js/README.md
Obsessively, consistently brand as `uPortal-home`.
~~Two~~ commits:
+ one for everything except actual artifact identifiers ("documentation"). This mostly won't break anything, though I suppose Jasig's picky `NOTICE` file checker will want downstream `NOTICE` files to reflect the change the next time the picky notice checker plugin runs on those projects.
+ ~~one for actual Maven artifactIds. BREAKING CHANGE. Using a goofy internal capital letter in these may be a bad idea, or at least may be unjustified.~~
~~Leading with thoroughly adopting the branding `uPortal-home` because this new name is young and now is the moment if we're going to do this, but **I could totally see dropping the artifact identifier changing commit from this and just doing the rest of the renaming** so as to not …
> Use name `uPortal-home` consistently

- web/src/main/webapp/my-app/layout/controllers.js
- web/src/main/webapp/my-app/layout/partials/remove-button.html
This is a conflict-free version of #699 
- Broke functionality for widget remove button into its own controller
- Replaced jQuery stuff with angular filters or plain javascript
The functionality used to live in `LayoutController`, and every instance of a `<remove-button>` in a user's layout was causing `LayoutController` to initialize (including the `getLayout()` service call. It's probably better if each instance of the remove button only initializes what it needs to function.
----
> fix: Separate remove button into own controller

- web/src/main/webapp/my-app/marketplace/controllers.js
This uses the [theme name refactor in uPortal-app-framework](https://github.com/uPortal-Project/uportal-app-framework/pull/568) to simplify getting the current theme's primary color.
----
> fix: using mdColors to get primary color in marketplace

- web/src/main/webapp/my-app/marketplace/partials/marketplace-entry.html
- web/src/main/webapp/my-app/search/partials/marketplace-results.html
Using a filter to determine if launch links in marketplace should have `noopener noreferrer`
----
> fix: calculating rel on marketplace anchors

- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
- web/src/main/webapp/my-app/layout/partials/default-view.html
- web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
- web/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
- web/src/main/webapp/my-app/marketplace/partials/marketplace.html
- web/src/main/webapp/my-app/search/partials/search-results.html
This is to allow uportal-home to leverage the changes made in [uportal-app-framework#588](https://github.com/uPortal-Project/uportal-app-framework/pull/588)
- Wrapped all pages in `frame-page` to enable side navigation menu to work as intended
- Fixed some bonkers formatting in details page HTML
----
> Use frame-page directive for all views

- web/src/main/webapp/my-app/layout/controllers.js
[MUMUP-3196](https://jira.doit.wisc.edu/jira/browse/MUMUP-3196): "As a user, I would like my removing a widget from my home to reflect in the UI so I am not frustrated and confused."
- Revert to manually calling `$scope.apply` on layout change
- Remove unused `removePortlet` function
----
> fix: remove widget from layout on first try

- web/src/main/webapp/karma.conf.js
- web/src/main/webapp/test/main.js
Currently the setup is to run tests in framework as well as app, this change sets it up so that it only runs the app tests by replacing files provided by the overlay.  This will resolve the failing tests here - https://github.com/uPortal-Project/uportal-home/pull/750
----
> test(setup): configure to only run tests in uPortal-Home not in framework

- appveyor.yml
Makes the unrelated "Error: EPERM: operation not permitted" errors going away.
This is a short term patch, https://github.com/uPortal-Project/uportal-app-framework/issues/346 is a better long term fix.
----
> ci(appveyor): resolve require js flakiness

- web/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html
- web/src/main/webapp/my-app/layout/static/partials/static-content-max.html
Addresses MUMUP-3231
before:
after:
----
> fix: use region-main in static and exclusive mode

- .travis.yml
- package-lock.json
- package.json
resolves #722, the deployment key based approach didn't work out.
If we want automated lockfile updates, renovate supports it without needing a secret key to be added to public CI.
----
> refactor: remove greenkeeper lockfile

- web/src/main/webapp/my-app/layout/controllers.js
dropindex seems to actually be undefined if you don't move it out of its place. This causes an error in the console. Test for undefined before testing for equal index.
----
> fix: dropindex undefined when not moved

- CHANGELOG.md
- web/src/main/webapp/my-app/marketplace/controllers.js
The app directory browse page currently can sort alphabetically, 
but prior to this changeset does so by [not-visible-to-users "name" (an administrative, internal label for content) rather than by the visible-to-users "title"](https://github.com/uPortal-Project/uportal-home/blob/master/docs/app-directory.md#title-and-name).
For most content these labels are the same, so it's an easy bug to overlook. Occasionally these labels are not the same, yielding a weird alphabetical sorting experience for users.
Incidentally encountered bug ( resolves #790 ) in trying to add mock data; seems a quick fix so taking a shot at it.
After:
----
[Contributor License Agreements]: …
> fix: A-Z sort apps by title, not name

- CHANGELOG.md
- package-lock.json
- package.json
- web/src/main/webapp/css/home.less
- web/src/main/webapp/js/dnd-lists.js
- web/src/main/webapp/main.js
- web/src/main/webapp/my-app/layout/controllers.js
- web/src/main/webapp/my-app/layout/directives.js
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
- web/src/main/webapp/my-app/layout/partials/default-view.html
- web/src/main/webapp/my-app/layout/spec/layout_controller_spec.js
- web/src/main/webapp/my-app/layout/spec/layout_services_spec.js
- web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
- web/src/main/webapp/my-app/main.js
[MUMUP-3249](https://jira.doit.wisc.edu/jira/browse/MUMUP-3249): "As a keyboard user I would like to re-order my layout so that I can customize my MyUW experience to my needs."
- Replace incompatible jQuery UI drag and drop implementation with angular-drag-and-drop-lists
- Using arrow keys while focusing a widget will move it up or down in the layout order
- Add initial focus point with aria label in list of widgets
- Add controls for compact mode
- Remove ui bootstrap layout implementation and replace with CSS-grid (with flex box fallback for unsupported browsers)
**Related PR:** [uportal-app-framework#721](https://github.com/uPortal-Project/uportal-app-framework/pull/721)
----
[Apereo CLA roster]: …
> feat: add keyboard controls for widget layout

- CHANGELOG.md
- web/src/main/webapp/my-app/search/controllers.js
- web/src/main/webapp/my-app/search/partials/search-results.html
Was bugged to always total to zero.
Removing the feature 
+ "fixes the bug"
+ reduces bulk of code to maintain and
+ is (arguably) no less clear a user experience.
Before:
After:
----
> fix: remove search total badge and controller support for

- CHANGELOG.md
- docs/README.md
- docs/impersonation.md
I was confused by what turned out to be a cache population side effect of client-side message (notification) resolution. I'd realized the importance of removing widgets with side effects from the home page before impersonating, but I hadn't realized that `HRSPortlet` caches would populate anyway thanks to side effect of resolving the statements `resourceURL` to audience filter a notification.
Having had the insight that messages can now have these cache population side effects, added documentation to reflect.
----
> docs: add impersonation.md documenting identity/attribute swapping

- CHANGELOG.md
- web/src/main/webapp/css/home.less
- web/src/main/webapp/css/my-app.less
- web/src/main/webapp/css/toast.less
- web/src/main/webapp/css/variables.less
- web/src/main/webapp/my-app/layout/controllers.js
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
- web/src/main/webapp/my-app/layout/partials/remove-button.html
- web/src/main/webapp/my-app/layout/partials/toast-widget-removal.html
- web/src/main/webapp/my-app/layout/spec/layout_controller_spec.js
- web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
[MUMUP-3095](https://jira.doit.wisc.edu/jira/browse/MUMUP-3095): "As a person who just deleted an item from my MyUW homepage, I'd like acknowledgement that I did this and the opportunity to undo it, so I can understand what I did and recover if it's not what I really want."
- Removing a widget can be undone via a toast message
- Toast resolves automatically after 3 seconds
- If user clicks "Undo" before resolution, the widget is added back to the layout
- If user deletes another widget before the first toast has resolved, it will automatically resolve it and show a new toast
- On large screens, toast appears in top right of application space
- On small screens, toast appears at bottom of screen (per Material specs)
- Removed unnecessary `LayoutController`. Expanded and …
> feat: prompt confirmation/undo when removing widgets from home

- CHANGELOG.md
Change to a typo'd version number in the CHANGELOG
----
> docs: fix Changelog link

- CHANGELOG.md
- web/src/main/webapp/css/toast.less
- web/src/main/webapp/my-app/layout/controllers.js
- web/src/main/webapp/my-app/layout/partials/toast-widget-removal.html
[MUMMNG-4155](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4155): "As a user who recently deleted a widget from my layout, I would like the opportunity to undo my action before the snackbar disappears, so that I may undo a delete if I want."
[Material guidelines for snackbars & toasts](https://material.io/guidelines/components/snackbars-toasts.html#)
- Increased time before auto-hide
- Removed customizations that made snackbars look like notifications
- No longer show widget icons in snackbar message
- Snackbar always appears fixed to bottom of viewport (so it's always visible)
----
> fix: tweak snackbars per material guidelines

- CHANGELOG.md
- docs/app-directory.md
Since we prefer Material Icons, be really clear how configure `portlet-definition`s to use them.
Since we're pursuing Material Design, **formally deprecate Font Awesome icon support** in the hope of encouraging natural movement to the preferred icon vocabulary. **(This may be controversial.)**
(I'm not sure I knew how to make use of Material icons as app directory icons before seeing a colleague do it locally -- documenting the magic name of the `parameter` not least so I myself will come across this documentation next time I'm bootstrapping the icon for an app directory entry.)
----
> docs(icons): Prefer Material icons and deprecate Font Awesome icons

- CHANGELOG.md
- web/src/main/webapp/css/search-results.less
- web/src/main/webapp/my-app/search/controllers.js
- web/src/main/webapp/my-app/search/partials/marketplace-results.html
- web/src/main/webapp/my-app/search/partials/search-results.html
[MUMMNG-4156](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4156): "As a MyUW user trying to find the enroll app ("Course Search and Enroll"), I want it to be the top result when I search for "enroll" or "enrollment", so that I'm not under the impression that it's not a thing."
- Order app search results by matching titles, then matching keywords/descriptions
- Removed alphabetical/popularity ordering (unused)
- Added a bit of text that shows the search term being used
----
> fix: app search results by title first

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/controllers.js
[MUMUP-3332](https://jira.doit.wisc.edu/jira/browse/MUMUP-3332): "As a MyUW user, I would like to be able to delete widgets quickly without waiting for the undo snackbar to elapse so that I can declutter my homepage with alacrity and decisiveness."
- Track widgets removed by user outside of toast promise cycle and follow through on removal whenever a toast's promise is resolved
- Clean up some unused code
----
> fix: better support rapid widget removal 

- CHANGELOG.md
Trivial. Just being obsessive.
`npm run lint-md` passes locally.
```
$ npm run lint-md
> @uportal/home@7.0.1 lint-md /Users/apetro/code/github_uportal/uportal-home
> remark . --frail --ignore-path .gitignore
CHANGELOG.md: no issues found
CODE_OF_CONDUCT.md: no issues found
README.md: no issues found
SUPPORT.md: no issues found
committers.md: no issues found
docs/README.md: no issues found
docs/apereo-incubation.md: no issues found
docs/app-directory.md: no issues found
docs/compact.md: no issues found
docs/contributors.md: no issues found
docs/expanded.md: no issues found
docs/impersonation.md: no issues found
docs/presentations.md: no issues found
docs/releasing.md: no issues found
docs/roadmap.md: no issues found
docs/screenshots.md: no issues found
docs/search.md: no issues found …
```
> style(changelog): blank lines around headings, wrap at 80 char

- CHANGELOG.md
- web/src/main/webapp/my-app/search/controllers.js
- web/src/main/webapp/my-app/search/partials/marketplace-results.html
Before: bugged: when search on a term that yields zero results from app directory, loading indicator keeps pointlessly spinning even though nothing more will be loaded.
After: loading indicator disappears when app directory content loads and filtering completes, even if that filtering yields zero relevant results.
> fix: hide loading indicator when app dir search returns zero results

- CHANGELOG.md
- web/src/main/webapp/my-app/search/controllers.js
- web/src/main/webapp/my-app/search/partials/search-results.html
Had been bugged such that no-search-results recovery suggestions would never show.
Change to show when there's no hope of results.
After: no results:
After: some results
> fix(search): show no-results div when no results

- CHANGELOG.md
- docs/search.md
I think it's time to admit we're not going to fix and maintain this feature soon.
Removing it will reduce friction in other development and maintenance of the search experience.
And there's no rule we can't reach into source history and pick up and run with this feature whenever that becomes the right thing to do.
> feat(search): deprecate Web search integration

- CHANGELOG.md
- docs/search.md
- web/src/main/webapp/js/web-config.js
query parameter changed from `term` to `search[term]`
> fix(search): successfully launch into today.wisc.edu from Madison theme

- CHANGELOG.md
- web/src/main/webapp/my-app/search/controllers.js
- web/src/main/webapp/my-app/search/partials/search-results.html
Differentiate zero results from loading and error states, in the badges on the app directory and person directory search results tabs. Intended to better set user expectations about whether results have returned and what they'll find on those tabs if they click *now*. Also intended to incidentally fix some kind of bug about the search results indicated on tab not staying in sync with the search results as displayed.
Refactors to move badge computation to controller rather than in partial, simplifying partial and moving this state change closer to where related state changes.
May need some user testing. Users might appreciate and delight in this nuance, especially on a slooooow connection, or they may find it hard to understand or annoying?
After:
> feat(search): nuance app and person dir search results badges

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
[MUMUP-3360](https://jira.doit.wisc.edu/jira/browse/MUMUP-3360): "As a MyUW compact widget mode user, I would like my re-ordering of my layout to persist, so that I can customize my layout and have those changes saved"
- Added a missing function call :(
----
> fix: persist layout changes in compact mode

- CHANGELOG.md
- web/src/main/webapp/css/home.less
- web/src/main/webapp/css/widget.less
- web/src/main/webapp/my-app/layout/partials/remove-button.html
[https://jira.doit.wisc.edu/jira/browse/MUMUP-3297](MUMUP-3297): "As a person navigating MyUW via keyboard, I would like the less-often-used controls associated with widgets on my home tucked away into a contextual menu, so that the primary navigation is simpler."
**Companion PR:** [uportal-app-framework #786](https://github.com/uPortal-Project/uportal-app-framework/pull/786)
- Make removal button a menu item 
- Change icon to delete icon
- Add button text
- Delete unused CSS
----
> fix: adjust widget remove button to fit contextual menu

- CHANGELOG.md
To be fair, at the time I thought the change may have fixed the bug, just like I said.
I now know definitively it does not fix the bug, so it's no longer true that it "may".
Working on actually fixing the bug, which will make for a much more interesting pull request, but in the meantime trying to keep the CHANGELOG honest enough to support a hypothetical release before I have this fix in.
----
> docs(changelog): remove premature recognition of not-yet-fixed bugfix

- CHANGELOG.md
- web/src/main/webapp/my-app/search/partials/search-results.html
Mitigates bug in which the badge indicates more results than are visible to user, by removing the unreliable badge.
Intended as temporary workaround. Suppresses a misleading badge until deeper fix to reliably show the correct number in the badge. 
Hypothesis: underlying bug is it's including in the badge count items on which user has `BROWSE` but not `SUBSCRIBE` whereas the user-visible results listing is only showing items on which user has both kinds of permission.
----
> fix: rm app directory search results count badge, temporarily

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
[MUMUP-3360](https://jira.doit.wisc.edu/jira/browse/MUMUP-3360): "As a MyUW compact widget mode user, I would like my re-ordering of my layout to persist, so that I can customize my layout and have those changes saved."
----
> fix: do not remove compact widgets when reordering

- web/src/main/webapp/main.js
supplemental to https://github.com/uPortal-Project/uportal-app-framework/pull/857
Need to do this here, because this file overwrites frame's main.js
----
> fix: initialize cssVars after bootstrapping app

- CHANGELOG.md
- web/src/main/webapp/my-app/menu/partials/app-menu-template.html
From "Toggle expanded widgets" to "Change tile size".  As I understand it, user testing flagged the status quo label as problematic.
Credit to @mrdahman for user testing that flagged this, heuristic analysis, input. Quite possibly additional credit will be due through additional iteration, testing, usability analysis.
This may take more iterations, and when it comes right down to it this UI control may need to be more stateful (dynamic label, look like a toggle or slider, ...) Would a tool tip help? Link to documentation?
Status quo:
After this change:
----
Tracked internally to MyUW as [MUMUP-3435](https://jira.doit.wisc.edu/jira/browse/MUMUP-3435).
----
[Contributor License …
> fix: usable language in widget mode toggle label

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html
- web/src/main/webapp/my-app/layout/static/partials/static-content-max.html
App rating UI control for `/web/static/{fname}` and `/web/exclusive/{fname}` never caught on, drop it.
----
Within MyUW, tracked as [MUMUP-3233](https://jira.doit.wisc.edu/jira/browse/MUMUP-3233)
----
> fix: rm "Rate {app}" button from exclusive and static partials

- web/src/main/webapp/main.js
removing watch configuration from cssVars, because it makes the loading excruciatingly slow in IE11. Delaying the init by one second, because trying to run it directly after the bootstrapping is too early for IE on the first render.
----
> fix: rm watch configuration from cssVars

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/static/partials/static-content-exclusive.html
- web/src/main/webapp/my-app/layout/static/partials/static-content-max.html
In practice nodeId is always (often?) -1, so instead use `fname` to generate HTML element IDs.
----
> fix: id static content div with fname rather than nodeId

- web/src/main/webapp/staticFeeds/messages.json
announcement type messages no longer supported, so remove those examples and the no longer supported properties from messages.json
----
> fix: rm no longer meaningful messages.json content

- CHANGELOG.md
- web/src/main/webapp/css/home.less
- Firefox doesn't like the CSS-grid for displaying compact widgets -- added a flexbox fallback to center-align the grid
----
> fix: add flexbox fallback for compact widget grid

- CHANGELOG.md
In 9.1.0 release had overlooked some sub-headings that needed change to reflect the release state change.
----
> docs: fix 9.1.0 sub-headings to reflect released 

- docs/search.md
- web/src/main/resources/endpoint.properties.example
MyUW no longer runs this proxy out of a uPortal-home embed, instead deploying a separate proxy instance, so as is these docs are confusing; with this change this is slightly less confusing.
----
> docs: remove wiscdirectory local proxy example

- web/src/main/webapp/my-app/search/partials/search-results.html
As a way to showcase widgets that launch searches.
----
> Add "Other" tab in search suggesting search widgets

- committers.md
Recognize Paulina Nogal as committer,
on the basis of [contributions to uPortal-app-framework](https://github.com/uPortal-Project/uportal-app-framework/commits?author=nogalpaulina).
See also in context of uPortal-app-framework: https://github.com/uPortal-Project/uportal-app-framework/pull/953 .
----
----
Tracked internally to MyUW as [MYUWADMIN-962](https://jira.doit.wisc.edu/jira/browse/MYUWADMIN-962).
> Recognize Paulina Nogal as committer

- .github/CONTRIBUTING.md
- CHANGELOG.md
- README.md
- package.json
Should get to a green checkmark on the Travis-CI build.
Also reduces commitments going forward to help keep that green checkmark and make feedback from Travis-CI more meaningful.
+ Discontinues attempting to practice Conventional Commits, and associated commit message linting
+ Stops linking to GitHub diffs from version numbers in Changelog
+ Slims Changelog down to just the changes in the semantically versioned product, and not the meta work that doesn't ship semantically versioned functional changes in the product.
----
> Restore the green check mark on the Travis-CI build

- .github/PULL_REQUEST_TEMPLATE.md
Review of MyUW against the (UW Office of Cybersecurity) [Risk Management Framework](https://it.wisc.edu/about/division-of-information-technology/strategic-operations-departments-people/cybersecurity/risk-management-framework) flagged a need to add process to ensure changes are reviewed for security impact.
This PR would add a checkbox to the Pull Request template to remind to examine changes for security impact.
----
----
Tracked internally to MyUW as [MUMMNG-4659](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4659).
> docs: add reminder to examine for security impact to PR template

- web/pom.xml
HEAD typically depends on framework snapshot so as to use latest framework in development; uses concrete release version momentarily when releasing.
----
> depend on snapshot not release

- CHANGELOG.md
- web/src/main/webapp/my-app/marketplace/controllers.js
- web/src/main/webapp/my-app/marketplace/partials/marketplace.html
Since users are no longer able to rate entries, stop sorting entries by rating when browsing. Sort alphabetically instead.
This unblocks truncating the ratings table to reduce friction in maintaining content.
Also, tell users how many entries match their browse filter.
Before:
After: 
----
> Remove "popularity" sorting in app directory browse

- CHANGELOG.md
- web/src/main/webapp/my-app/marketplace/partials/marketplace-details.html
On the details page about an app directory entry, when previewing its widget, omit the context menu on the widget.
It contains the description, which is already rendered on the page, and a link to the details page, the selfsame page the
user is already looking at.
Makes the details page slightly less busy, and demonstrates the new `include-context-menu` attribute on the `widget` directive.
----
> omit widget context menu on widget on details page

- web/pom.xml
uPortal-home:master routinely relies upon latest SNAPSHOT produced by uPortal-app-framework:master . When releasing, app-framework produces a release version, and the uPortal-home release depends upon that release version for its release and then past the release again depends upon the latest SNAPSHOT. In this way uPortal-home releases depend upon stable versioned releases of app framework, but routine development and deployment of latest uPortal-home (e.g. on predev) routinely demonstrates against latest app framework.
----
> Use uportal-app-framework 17.0.3-SNAPSHOT

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/services.js
Automates migrating from old layout back-end to new back-end.
If the user is new to the new back-end,
query their layout from the old back end and publish it to the new back-end.
Otherwise, just use the new back-end.
Credit to @nogalpaulina : this resulted from working on this together.
> Migrate old layouts to new

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/directives.js
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
- web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
Remove ineffectual `KeepFocus` directive. There are no comments related to the purpose of this directive, and therefore I would like to propose removing it from the app, as it's putting the focus on unexpected elements.
----
> Remove KeepFocus directive

- web/src/main/webapp/my-app/layout/services.js
There are three spots in the code that can fire a redirect in response to a layout call failing. Status quo they all use the same source String, so it's hard to disambiguate which one is firing looking at console logs. This would give them each a different String.
> disambiguate the 3 "layout call" redirects

- web/src/main/webapp/my-app/layout/services.js
Addresses the easy-to-address nonstandard style flagged by eslint.
Before: more lines lighting up
After: fewer lines lighting up
No functional change.
> style: address some eslint flagged issues in /layout/services.js 

- CHANGELOG.md
- web/src/main/webapp/my-app/layout/services.js
The new layout backend [assures no duplicates](https://git.doit.wisc.edu/myuw/layout-service/-/blob/main/test/layout_service/core_test.clj#L361).
But when migrating layouts, this front end would POST the copied over layout to the new backend, but did not read the layout back out of the new backend, and so did not immediately benefit from the backend's de-duplication.
This Pull Request adds using Set to filter away duplicate fnames client-side during the migration process.
> drop duplicate fnames when migrating layout from old layout backend

- CHANGELOG.md
- web/src/main/webapp/css/home.less
Removes white border style when hovering over 'Add more to home' on compact layout
Before:
After:
----
> Removes white border style when hovering over 'Add more to home'

- CHANGELOG.md
- web/src/main/webapp/css/home.less
- web/src/main/webapp/my-app/layout/list/partials/home-list-view.html
- web/src/main/webapp/my-app/layout/partials/marketplace-light.html
- web/src/main/webapp/my-app/layout/widget/partials/home-widget-view.html
+ Adds tabindex to Add to home button as a fix for the button being inaccessible in Firefox.
Our developer noticed that Add to home isn't in the tab order (Both in expanded and in compact widget modes) when tabbing in Firefox 96.0 and in Safari 15.2 in the production environment. There's no evidence in the code that this interactive element was removed from the tab order, and should be accessible by default since it's a link `<a>`. I'm adding a `taindex="0"` to this element to ensure it's accessible in all browsers.
+ Removes unnecessary tabindex from list items surrounding widgets.
`tabindex="0"` was applied to `<li>` elements surrounding the actual widgets. This was causing additional and unnecessary steps when tabbing through the application's content.
----
Review for security …
> Improve accessibility of tabbing through widgets in compact mode

- web/pom.xml
build on [latest SNAPSHOT of uPortal-app-framework](https://github.com/uPortal-Project/uportal-app-framework/blob/master/pom.xml#L27), so that latest snapshot of uPortal-home builds on latest snapshot of uPortal-app-framework so that an environment running uPortal-home latest snapshot is using the latest everything.
> build on frame 21.0.4-SNAPSHOT
